// AUTOGENERATED by scripts/gen_bs58.py — do not edit by hand.

// 58^5 — the base of each carry-propagated chunk.
pub(crate) const R1: u64 = 656356768;

/// Convert a 32-byte big-endian integer (passed as 8 u32s in big-endian
/// order: $b0 is the high word) into 9 base-58^5 chunks, with carry already
/// propagated. The chunks $c7_0..$c0_8 are injected as `let` bindings into
/// the caller's scope, each in [0, 58^5).
///
/// Layout of the implied 45 base58 digits, in order (digit 0 is highest):
///   $c7_0 → digits 0..5       (digit 0 always 0 for any 32-byte input)
///   $c7_1 → digits 5..10
///   $c6_2 → digits 10..15
///   $c5_3 → digits 15..20
///   $c4_4 → digits 20..25
///   $c3_5 → digits 25..30
///   $c2_6 → digits 30..35
///   $c1_7 → digits 35..40
///   $c0_8 → digits 40..45
///
/// To extract digit i (0..45) of chunk c:
///   digit_i = (c / DIVISORS[i % 5]) % 58
///   where DIVISORS = [11316496, 195112, 3364, 58, 1]  // 58^4..58^0
#[macro_export]
macro_rules! base58_chunks {
    ($b0:expr, $b1:expr, $b2:expr, $b3:expr,
     $b4:expr, $b5:expr, $b6:expr, $b7:expr,
     $c7_0:ident, $c7_1:ident, $c6_2:ident, $c5_3:ident, $c4_4:ident,
     $c3_5:ident, $c2_6:ident, $c1_7:ident, $c0_8:ident) => {
        let bin0: u32 = $b0;
        let bin1: u32 = $b1;
        let bin2: u32 = $b2;
        let bin3: u32 = $b3;
        let bin4: u32 = $b4;
        let bin5: u32 = $b5;
        let bin6: u32 = $b6;
        let bin7: u32 = $b7;

        // base-58^5 multiply-accumulates (compile-time-constant table inlined).
        let im0: u64 = 0;

        let im1: u64 = bin0 as u64 * 513735u64;
        let im2: u64 = bin0 as u64 * 77223048u64 + bin1 as u64 * 78508u64;
        let im3: u64 = bin0 as u64 * 437087610u64 + bin1 as u64 * 646269101u64 + bin2 as u64 * 11997u64;
        let im4: u64 = bin0 as u64 * 300156666u64 + bin1 as u64 * 118408823u64 + bin2 as u64 * 486083817u64 + bin3 as u64 * 1833u64;
        let im5: u64 = bin0 as u64 * 605448490u64 + bin1 as u64 * 91512303u64 + bin2 as u64 * 3737691u64 + bin3 as u64 * 324463681u64 + bin4 as u64 * 280u64;
        let im6: u64 = bin0 as u64 * 214625350u64 + bin1 as u64 * 209184527u64 + bin2 as u64 * 294005210u64 + bin3 as u64 * 385795061u64 + bin4 as u64 * 127692781u64 + bin5 as u64 * 42u64;
        let im7: u64 = bin0 as u64 * 141436834u64 + bin1 as u64 * 413102373u64 + bin2 as u64 * 247894721u64 + bin3 as u64 * 551597588u64 + bin4 as u64 * 389432875u64 + bin5 as u64 * 537767569u64 + bin6 as u64 * 6u64;
        let im8: u64 = bin0 as u64 * 379377856u64 + bin1 as u64 * 153715680u64 + bin2 as u64 * 289024608u64 + bin3 as u64 * 21339008u64 + bin4 as u64 * 357132832u64 + bin5 as u64 * 410450016u64 + bin6 as u64 * 356826688u64 + bin7 as u64 * 1u64;

        // carry propagation: chunks ripple from low (im8) to high (im0).
        const __R1: u64 = $crate::kernels::base58::R1;

        let k0_7: u64 = im7 + (im8 / __R1);
        let k0_8: u64 = im8 % __R1;
        let k1_6: u64 = im6 + (k0_7 / __R1);
        let k1_7: u64 = k0_7 % __R1;
        let k2_5: u64 = im5 + (k1_6 / __R1);
        let k2_6: u64 = k1_6 % __R1;
        let k3_4: u64 = im4 + (k2_5 / __R1);
        let k3_5: u64 = k2_5 % __R1;
        let k4_3: u64 = im3 + (k3_4 / __R1);
        let k4_4: u64 = k3_4 % __R1;
        let k5_2: u64 = im2 + (k4_3 / __R1);
        let k5_3: u64 = k4_3 % __R1;
        let k6_1: u64 = im1 + (k5_2 / __R1);
        let k6_2: u64 = k5_2 % __R1;
        let k7_0: u64 = im0 + (k6_1 / __R1);
        let k7_1: u64 = k6_1 % __R1;

        // inject as caller-named u32 locals (each fits in u32 since R1 < 2^30).
        let $c7_0: u32 = k7_0 as u32;
        let $c7_1: u32 = k7_1 as u32;
        let $c6_2: u32 = k6_2 as u32;
        let $c5_3: u32 = k5_3 as u32;
        let $c4_4: u32 = k4_4 as u32;
        let $c3_5: u32 = k3_5 as u32;
        let $c2_6: u32 = k2_6 as u32;
        let $c1_7: u32 = k1_7 as u32;
        let $c0_8: u32 = k0_8 as u32;
    };
}

