// AUTOGENERATED by scripts/gen_sha.py — do not edit by hand.

// Small inline helpers. Emitted as `pub(crate) fn #[inline(always)]` because
// they're tiny (3-5 ops) and rustc's MIR inliner folds them into the caller
// before cuda-oxide's collector ever sees them as standalone items —
// confirmed: no `vanity__kernels__sha256__ep0` etc. in the emitted PTX.

#[inline(always)]
pub(crate) fn ep0(x: u32) -> u32 { x.rotate_right(2) ^ x.rotate_right(13) ^ x.rotate_right(22) }
#[inline(always)]
pub(crate) fn ep1(x: u32) -> u32 { x.rotate_right(6) ^ x.rotate_right(11) ^ x.rotate_right(25) }
#[inline(always)]
pub(crate) fn sig0(x: u32) -> u32 { x.rotate_right(7) ^ x.rotate_right(18) ^ (x >> 3) }
#[inline(always)]
pub(crate) fn sig1(x: u32) -> u32 { x.rotate_right(17) ^ x.rotate_right(19) ^ (x >> 10) }
#[inline(always)]
pub(crate) fn ch(x: u32, y: u32, z: u32) -> u32 { (x & y) ^ (!x & z) }
#[inline(always)]
pub(crate) fn maj(x: u32, y: u32, z: u32) -> u32 { (x & y) ^ (x & z) ^ (y & z) }

/// Hash base[32] || seed[16] || owner[32] (80 bytes) and inject the 8 u32
/// result words as named `let` bindings into the caller's scope.
///
/// **Midstate optimisation**: rounds 0..7 of block 1's compress depend only on
/// the SHA initial state and W[0..7] = base — both loop-invariant. cuda-oxide's
/// codegen wasn't const-folding the round-0..7 `llvm.fshr.i32(const,const,k)`
/// calls out of the inner loop, so we precompute the post-round-7 state
/// (`$st0..$st7`) on the host and pass it in. The kernel starts compress at
/// round 8.
///
/// W[16..22] of the message schedule still references W[0..7] = base, so we
/// also pass `$b0..$b7` so the macro can do sig0(base)+base adds. LLVM is
/// happy with those because `$b*` are kernel `.param` values.
///
/// Args:
///   $st0..$st7: u32 — state after rounds 0..7 of block 1 (host-precomputed)
///   $b0..$b7  : u32 — base bytes 0..32 as BE words (b0 holds bytes 0..4)
///   $s0..$s3  : u32 — seed bytes 0..16 BE-packed
///   $o0..$o7  : u32 — owner bytes 0..32 as BE words
///   $kw2      : ident — name of a `SharedArray<u32, 64>` containing
///                       host-precomputed `K[i] + W[i]` for block 2.
///   $h0..$h7  : ident — caller-named locals to receive the digest words.
#[macro_export]
macro_rules! sha256_80 {
    ($st0:expr, $st1:expr, $st2:expr, $st3:expr,
     $st4:expr, $st5:expr, $st6:expr, $st7:expr,
     $b0:expr, $b1:expr, $b2:expr, $b3:expr,
     $b4:expr, $b5:expr, $b6:expr, $b7:expr,
     $s0:expr, $s1:expr, $s2:expr, $s3:expr,
     $o0:expr, $o1:expr, $o2:expr, $o3:expr,
     $o4:expr, $o5:expr, $o6:expr, $o7:expr,
     $kw2:ident,
     $h0:ident, $h1:ident, $h2:ident, $h3:ident,
     $h4:ident, $h5:ident, $h6:ident, $h7:ident) => {
        let __mid_a: u32 = $st0; let __mid_b: u32 = $st1;
        let __mid_c: u32 = $st2; let __mid_d: u32 = $st3;
        let __mid_e: u32 = $st4; let __mid_f: u32 = $st5;
        let __mid_g: u32 = $st6; let __mid_h: u32 = $st7;
        let __base_w0: u32 = $b0; let __base_w1: u32 = $b1;
        let __base_w2: u32 = $b2; let __base_w3: u32 = $b3;
        let __base_w4: u32 = $b4; let __base_w5: u32 = $b5;
        let __base_w6: u32 = $b6; let __base_w7: u32 = $b7;
        let __seed_w0: u32 = $s0; let __seed_w1: u32 = $s1;
        let __seed_w2: u32 = $s2; let __seed_w3: u32 = $s3;
        let __owner_w0: u32 = $o0; let __owner_w1: u32 = $o1;
        let __owner_w2: u32 = $o2; let __owner_w3: u32 = $o3;
        let __owner_w4: u32 = $o4; let __owner_w5: u32 = $o5;
        let __owner_w6: u32 = $o6; let __owner_w7: u32 = $o7;

        let ma00: u32 = __base_w0;
        let ma01: u32 = __base_w1;
        let ma02: u32 = __base_w2;
        let ma03: u32 = __base_w3;
        let ma04: u32 = __base_w4;
        let ma05: u32 = __base_w5;
        let ma06: u32 = __base_w6;
        let ma07: u32 = __base_w7;
        let ma08: u32 = __seed_w0;
        let ma09: u32 = __seed_w1;
        let ma10: u32 = __seed_w2;
        let ma11: u32 = __seed_w3;
        let ma12: u32 = __owner_w0;
        let ma13: u32 = __owner_w1;
        let ma14: u32 = __owner_w2;
        let ma15: u32 = __owner_w3;
        let ma16: u32 = $crate::kernels::sha256::sig1(ma14).wrapping_add(ma09).wrapping_add($crate::kernels::sha256::sig0(ma01)).wrapping_add(ma00);
        let ma17: u32 = $crate::kernels::sha256::sig1(ma15).wrapping_add(ma10).wrapping_add($crate::kernels::sha256::sig0(ma02)).wrapping_add(ma01);
        let ma18: u32 = $crate::kernels::sha256::sig1(ma16).wrapping_add(ma11).wrapping_add($crate::kernels::sha256::sig0(ma03)).wrapping_add(ma02);
        let ma19: u32 = $crate::kernels::sha256::sig1(ma17).wrapping_add(ma12).wrapping_add($crate::kernels::sha256::sig0(ma04)).wrapping_add(ma03);
        let ma20: u32 = $crate::kernels::sha256::sig1(ma18).wrapping_add(ma13).wrapping_add($crate::kernels::sha256::sig0(ma05)).wrapping_add(ma04);
        let ma21: u32 = $crate::kernels::sha256::sig1(ma19).wrapping_add(ma14).wrapping_add($crate::kernels::sha256::sig0(ma06)).wrapping_add(ma05);
        let ma22: u32 = $crate::kernels::sha256::sig1(ma20).wrapping_add(ma15).wrapping_add($crate::kernels::sha256::sig0(ma07)).wrapping_add(ma06);
        let ma23: u32 = $crate::kernels::sha256::sig1(ma21).wrapping_add(ma16).wrapping_add($crate::kernels::sha256::sig0(ma08)).wrapping_add(ma07);
        let ma24: u32 = $crate::kernels::sha256::sig1(ma22).wrapping_add(ma17).wrapping_add($crate::kernels::sha256::sig0(ma09)).wrapping_add(ma08);
        let ma25: u32 = $crate::kernels::sha256::sig1(ma23).wrapping_add(ma18).wrapping_add($crate::kernels::sha256::sig0(ma10)).wrapping_add(ma09);
        let ma26: u32 = $crate::kernels::sha256::sig1(ma24).wrapping_add(ma19).wrapping_add($crate::kernels::sha256::sig0(ma11)).wrapping_add(ma10);
        let ma27: u32 = $crate::kernels::sha256::sig1(ma25).wrapping_add(ma20).wrapping_add($crate::kernels::sha256::sig0(ma12)).wrapping_add(ma11);
        let ma28: u32 = $crate::kernels::sha256::sig1(ma26).wrapping_add(ma21).wrapping_add($crate::kernels::sha256::sig0(ma13)).wrapping_add(ma12);
        let ma29: u32 = $crate::kernels::sha256::sig1(ma27).wrapping_add(ma22).wrapping_add($crate::kernels::sha256::sig0(ma14)).wrapping_add(ma13);
        let ma30: u32 = $crate::kernels::sha256::sig1(ma28).wrapping_add(ma23).wrapping_add($crate::kernels::sha256::sig0(ma15)).wrapping_add(ma14);
        let ma31: u32 = $crate::kernels::sha256::sig1(ma29).wrapping_add(ma24).wrapping_add($crate::kernels::sha256::sig0(ma16)).wrapping_add(ma15);
        let ma32: u32 = $crate::kernels::sha256::sig1(ma30).wrapping_add(ma25).wrapping_add($crate::kernels::sha256::sig0(ma17)).wrapping_add(ma16);
        let ma33: u32 = $crate::kernels::sha256::sig1(ma31).wrapping_add(ma26).wrapping_add($crate::kernels::sha256::sig0(ma18)).wrapping_add(ma17);
        let ma34: u32 = $crate::kernels::sha256::sig1(ma32).wrapping_add(ma27).wrapping_add($crate::kernels::sha256::sig0(ma19)).wrapping_add(ma18);
        let ma35: u32 = $crate::kernels::sha256::sig1(ma33).wrapping_add(ma28).wrapping_add($crate::kernels::sha256::sig0(ma20)).wrapping_add(ma19);
        let ma36: u32 = $crate::kernels::sha256::sig1(ma34).wrapping_add(ma29).wrapping_add($crate::kernels::sha256::sig0(ma21)).wrapping_add(ma20);
        let ma37: u32 = $crate::kernels::sha256::sig1(ma35).wrapping_add(ma30).wrapping_add($crate::kernels::sha256::sig0(ma22)).wrapping_add(ma21);
        let ma38: u32 = $crate::kernels::sha256::sig1(ma36).wrapping_add(ma31).wrapping_add($crate::kernels::sha256::sig0(ma23)).wrapping_add(ma22);
        let ma39: u32 = $crate::kernels::sha256::sig1(ma37).wrapping_add(ma32).wrapping_add($crate::kernels::sha256::sig0(ma24)).wrapping_add(ma23);
        let ma40: u32 = $crate::kernels::sha256::sig1(ma38).wrapping_add(ma33).wrapping_add($crate::kernels::sha256::sig0(ma25)).wrapping_add(ma24);
        let ma41: u32 = $crate::kernels::sha256::sig1(ma39).wrapping_add(ma34).wrapping_add($crate::kernels::sha256::sig0(ma26)).wrapping_add(ma25);
        let ma42: u32 = $crate::kernels::sha256::sig1(ma40).wrapping_add(ma35).wrapping_add($crate::kernels::sha256::sig0(ma27)).wrapping_add(ma26);
        let ma43: u32 = $crate::kernels::sha256::sig1(ma41).wrapping_add(ma36).wrapping_add($crate::kernels::sha256::sig0(ma28)).wrapping_add(ma27);
        let ma44: u32 = $crate::kernels::sha256::sig1(ma42).wrapping_add(ma37).wrapping_add($crate::kernels::sha256::sig0(ma29)).wrapping_add(ma28);
        let ma45: u32 = $crate::kernels::sha256::sig1(ma43).wrapping_add(ma38).wrapping_add($crate::kernels::sha256::sig0(ma30)).wrapping_add(ma29);
        let ma46: u32 = $crate::kernels::sha256::sig1(ma44).wrapping_add(ma39).wrapping_add($crate::kernels::sha256::sig0(ma31)).wrapping_add(ma30);
        let ma47: u32 = $crate::kernels::sha256::sig1(ma45).wrapping_add(ma40).wrapping_add($crate::kernels::sha256::sig0(ma32)).wrapping_add(ma31);
        let ma48: u32 = $crate::kernels::sha256::sig1(ma46).wrapping_add(ma41).wrapping_add($crate::kernels::sha256::sig0(ma33)).wrapping_add(ma32);
        let ma49: u32 = $crate::kernels::sha256::sig1(ma47).wrapping_add(ma42).wrapping_add($crate::kernels::sha256::sig0(ma34)).wrapping_add(ma33);
        let ma50: u32 = $crate::kernels::sha256::sig1(ma48).wrapping_add(ma43).wrapping_add($crate::kernels::sha256::sig0(ma35)).wrapping_add(ma34);
        let ma51: u32 = $crate::kernels::sha256::sig1(ma49).wrapping_add(ma44).wrapping_add($crate::kernels::sha256::sig0(ma36)).wrapping_add(ma35);
        let ma52: u32 = $crate::kernels::sha256::sig1(ma50).wrapping_add(ma45).wrapping_add($crate::kernels::sha256::sig0(ma37)).wrapping_add(ma36);
        let ma53: u32 = $crate::kernels::sha256::sig1(ma51).wrapping_add(ma46).wrapping_add($crate::kernels::sha256::sig0(ma38)).wrapping_add(ma37);
        let ma54: u32 = $crate::kernels::sha256::sig1(ma52).wrapping_add(ma47).wrapping_add($crate::kernels::sha256::sig0(ma39)).wrapping_add(ma38);
        let ma55: u32 = $crate::kernels::sha256::sig1(ma53).wrapping_add(ma48).wrapping_add($crate::kernels::sha256::sig0(ma40)).wrapping_add(ma39);
        let ma56: u32 = $crate::kernels::sha256::sig1(ma54).wrapping_add(ma49).wrapping_add($crate::kernels::sha256::sig0(ma41)).wrapping_add(ma40);
        let ma57: u32 = $crate::kernels::sha256::sig1(ma55).wrapping_add(ma50).wrapping_add($crate::kernels::sha256::sig0(ma42)).wrapping_add(ma41);
        let ma58: u32 = $crate::kernels::sha256::sig1(ma56).wrapping_add(ma51).wrapping_add($crate::kernels::sha256::sig0(ma43)).wrapping_add(ma42);
        let ma59: u32 = $crate::kernels::sha256::sig1(ma57).wrapping_add(ma52).wrapping_add($crate::kernels::sha256::sig0(ma44)).wrapping_add(ma43);
        let ma60: u32 = $crate::kernels::sha256::sig1(ma58).wrapping_add(ma53).wrapping_add($crate::kernels::sha256::sig0(ma45)).wrapping_add(ma44);
        let ma61: u32 = $crate::kernels::sha256::sig1(ma59).wrapping_add(ma54).wrapping_add($crate::kernels::sha256::sig0(ma46)).wrapping_add(ma45);
        let ma62: u32 = $crate::kernels::sha256::sig1(ma60).wrapping_add(ma55).wrapping_add($crate::kernels::sha256::sig0(ma47)).wrapping_add(ma46);
        let ma63: u32 = $crate::kernels::sha256::sig1(ma61).wrapping_add(ma56).wrapping_add($crate::kernels::sha256::sig0(ma48)).wrapping_add(ma47);
        let mut a = __mid_a;
        let mut b = __mid_b;
        let mut c = __mid_c;
        let mut d = __mid_d;
        let mut e = __mid_e;
        let mut f = __mid_f;
        let mut g = __mid_g;
        let mut h = __mid_h;
        // round 8
        {
            let t1 = h.wrapping_add($crate::kernels::sha256::ep1(e)).wrapping_add($crate::kernels::sha256::ch(e, f, g)).wrapping_add(0xd807aa98u32.wrapping_add(ma08));
            let t2 = $crate::kernels::sha256::ep0(a).wrapping_add($crate::kernels::sha256::maj(a, b, c));
            h = g; g = f; f = e; e = d.wrapping_add(t1); d = c; c = b; b = a; a = t1.wrapping_add(t2);
        }
        // round 9
        {
            let t1 = h.wrapping_add($crate::kernels::sha256::ep1(e)).wrapping_add($crate::kernels::sha256::ch(e, f, g)).wrapping_add(0x12835b01u32.wrapping_add(ma09));
            let t2 = $crate::kernels::sha256::ep0(a).wrapping_add($crate::kernels::sha256::maj(a, b, c));
            h = g; g = f; f = e; e = d.wrapping_add(t1); d = c; c = b; b = a; a = t1.wrapping_add(t2);
        }
        // round 10
        {
            let t1 = h.wrapping_add($crate::kernels::sha256::ep1(e)).wrapping_add($crate::kernels::sha256::ch(e, f, g)).wrapping_add(0x243185beu32.wrapping_add(ma10));
            let t2 = $crate::kernels::sha256::ep0(a).wrapping_add($crate::kernels::sha256::maj(a, b, c));
            h = g; g = f; f = e; e = d.wrapping_add(t1); d = c; c = b; b = a; a = t1.wrapping_add(t2);
        }
        // round 11
        {
            let t1 = h.wrapping_add($crate::kernels::sha256::ep1(e)).wrapping_add($crate::kernels::sha256::ch(e, f, g)).wrapping_add(0x550c7dc3u32.wrapping_add(ma11));
            let t2 = $crate::kernels::sha256::ep0(a).wrapping_add($crate::kernels::sha256::maj(a, b, c));
            h = g; g = f; f = e; e = d.wrapping_add(t1); d = c; c = b; b = a; a = t1.wrapping_add(t2);
        }
        // round 12
        {
            let t1 = h.wrapping_add($crate::kernels::sha256::ep1(e)).wrapping_add($crate::kernels::sha256::ch(e, f, g)).wrapping_add(0x72be5d74u32.wrapping_add(ma12));
            let t2 = $crate::kernels::sha256::ep0(a).wrapping_add($crate::kernels::sha256::maj(a, b, c));
            h = g; g = f; f = e; e = d.wrapping_add(t1); d = c; c = b; b = a; a = t1.wrapping_add(t2);
        }
        // round 13
        {
            let t1 = h.wrapping_add($crate::kernels::sha256::ep1(e)).wrapping_add($crate::kernels::sha256::ch(e, f, g)).wrapping_add(0x80deb1feu32.wrapping_add(ma13));
            let t2 = $crate::kernels::sha256::ep0(a).wrapping_add($crate::kernels::sha256::maj(a, b, c));
            h = g; g = f; f = e; e = d.wrapping_add(t1); d = c; c = b; b = a; a = t1.wrapping_add(t2);
        }
        // round 14
        {
            let t1 = h.wrapping_add($crate::kernels::sha256::ep1(e)).wrapping_add($crate::kernels::sha256::ch(e, f, g)).wrapping_add(0x9bdc06a7u32.wrapping_add(ma14));
            let t2 = $crate::kernels::sha256::ep0(a).wrapping_add($crate::kernels::sha256::maj(a, b, c));
            h = g; g = f; f = e; e = d.wrapping_add(t1); d = c; c = b; b = a; a = t1.wrapping_add(t2);
        }
        // round 15
        {
            let t1 = h.wrapping_add($crate::kernels::sha256::ep1(e)).wrapping_add($crate::kernels::sha256::ch(e, f, g)).wrapping_add(0xc19bf174u32.wrapping_add(ma15));
            let t2 = $crate::kernels::sha256::ep0(a).wrapping_add($crate::kernels::sha256::maj(a, b, c));
            h = g; g = f; f = e; e = d.wrapping_add(t1); d = c; c = b; b = a; a = t1.wrapping_add(t2);
        }
        // round 16
        {
            let t1 = h.wrapping_add($crate::kernels::sha256::ep1(e)).wrapping_add($crate::kernels::sha256::ch(e, f, g)).wrapping_add(0xe49b69c1u32.wrapping_add(ma16));
            let t2 = $crate::kernels::sha256::ep0(a).wrapping_add($crate::kernels::sha256::maj(a, b, c));
            h = g; g = f; f = e; e = d.wrapping_add(t1); d = c; c = b; b = a; a = t1.wrapping_add(t2);
        }
        // round 17
        {
            let t1 = h.wrapping_add($crate::kernels::sha256::ep1(e)).wrapping_add($crate::kernels::sha256::ch(e, f, g)).wrapping_add(0xefbe4786u32.wrapping_add(ma17));
            let t2 = $crate::kernels::sha256::ep0(a).wrapping_add($crate::kernels::sha256::maj(a, b, c));
            h = g; g = f; f = e; e = d.wrapping_add(t1); d = c; c = b; b = a; a = t1.wrapping_add(t2);
        }
        // round 18
        {
            let t1 = h.wrapping_add($crate::kernels::sha256::ep1(e)).wrapping_add($crate::kernels::sha256::ch(e, f, g)).wrapping_add(0x0fc19dc6u32.wrapping_add(ma18));
            let t2 = $crate::kernels::sha256::ep0(a).wrapping_add($crate::kernels::sha256::maj(a, b, c));
            h = g; g = f; f = e; e = d.wrapping_add(t1); d = c; c = b; b = a; a = t1.wrapping_add(t2);
        }
        // round 19
        {
            let t1 = h.wrapping_add($crate::kernels::sha256::ep1(e)).wrapping_add($crate::kernels::sha256::ch(e, f, g)).wrapping_add(0x240ca1ccu32.wrapping_add(ma19));
            let t2 = $crate::kernels::sha256::ep0(a).wrapping_add($crate::kernels::sha256::maj(a, b, c));
            h = g; g = f; f = e; e = d.wrapping_add(t1); d = c; c = b; b = a; a = t1.wrapping_add(t2);
        }
        // round 20
        {
            let t1 = h.wrapping_add($crate::kernels::sha256::ep1(e)).wrapping_add($crate::kernels::sha256::ch(e, f, g)).wrapping_add(0x2de92c6fu32.wrapping_add(ma20));
            let t2 = $crate::kernels::sha256::ep0(a).wrapping_add($crate::kernels::sha256::maj(a, b, c));
            h = g; g = f; f = e; e = d.wrapping_add(t1); d = c; c = b; b = a; a = t1.wrapping_add(t2);
        }
        // round 21
        {
            let t1 = h.wrapping_add($crate::kernels::sha256::ep1(e)).wrapping_add($crate::kernels::sha256::ch(e, f, g)).wrapping_add(0x4a7484aau32.wrapping_add(ma21));
            let t2 = $crate::kernels::sha256::ep0(a).wrapping_add($crate::kernels::sha256::maj(a, b, c));
            h = g; g = f; f = e; e = d.wrapping_add(t1); d = c; c = b; b = a; a = t1.wrapping_add(t2);
        }
        // round 22
        {
            let t1 = h.wrapping_add($crate::kernels::sha256::ep1(e)).wrapping_add($crate::kernels::sha256::ch(e, f, g)).wrapping_add(0x5cb0a9dcu32.wrapping_add(ma22));
            let t2 = $crate::kernels::sha256::ep0(a).wrapping_add($crate::kernels::sha256::maj(a, b, c));
            h = g; g = f; f = e; e = d.wrapping_add(t1); d = c; c = b; b = a; a = t1.wrapping_add(t2);
        }
        // round 23
        {
            let t1 = h.wrapping_add($crate::kernels::sha256::ep1(e)).wrapping_add($crate::kernels::sha256::ch(e, f, g)).wrapping_add(0x76f988dau32.wrapping_add(ma23));
            let t2 = $crate::kernels::sha256::ep0(a).wrapping_add($crate::kernels::sha256::maj(a, b, c));
            h = g; g = f; f = e; e = d.wrapping_add(t1); d = c; c = b; b = a; a = t1.wrapping_add(t2);
        }
        // round 24
        {
            let t1 = h.wrapping_add($crate::kernels::sha256::ep1(e)).wrapping_add($crate::kernels::sha256::ch(e, f, g)).wrapping_add(0x983e5152u32.wrapping_add(ma24));
            let t2 = $crate::kernels::sha256::ep0(a).wrapping_add($crate::kernels::sha256::maj(a, b, c));
            h = g; g = f; f = e; e = d.wrapping_add(t1); d = c; c = b; b = a; a = t1.wrapping_add(t2);
        }
        // round 25
        {
            let t1 = h.wrapping_add($crate::kernels::sha256::ep1(e)).wrapping_add($crate::kernels::sha256::ch(e, f, g)).wrapping_add(0xa831c66du32.wrapping_add(ma25));
            let t2 = $crate::kernels::sha256::ep0(a).wrapping_add($crate::kernels::sha256::maj(a, b, c));
            h = g; g = f; f = e; e = d.wrapping_add(t1); d = c; c = b; b = a; a = t1.wrapping_add(t2);
        }
        // round 26
        {
            let t1 = h.wrapping_add($crate::kernels::sha256::ep1(e)).wrapping_add($crate::kernels::sha256::ch(e, f, g)).wrapping_add(0xb00327c8u32.wrapping_add(ma26));
            let t2 = $crate::kernels::sha256::ep0(a).wrapping_add($crate::kernels::sha256::maj(a, b, c));
            h = g; g = f; f = e; e = d.wrapping_add(t1); d = c; c = b; b = a; a = t1.wrapping_add(t2);
        }
        // round 27
        {
            let t1 = h.wrapping_add($crate::kernels::sha256::ep1(e)).wrapping_add($crate::kernels::sha256::ch(e, f, g)).wrapping_add(0xbf597fc7u32.wrapping_add(ma27));
            let t2 = $crate::kernels::sha256::ep0(a).wrapping_add($crate::kernels::sha256::maj(a, b, c));
            h = g; g = f; f = e; e = d.wrapping_add(t1); d = c; c = b; b = a; a = t1.wrapping_add(t2);
        }
        // round 28
        {
            let t1 = h.wrapping_add($crate::kernels::sha256::ep1(e)).wrapping_add($crate::kernels::sha256::ch(e, f, g)).wrapping_add(0xc6e00bf3u32.wrapping_add(ma28));
            let t2 = $crate::kernels::sha256::ep0(a).wrapping_add($crate::kernels::sha256::maj(a, b, c));
            h = g; g = f; f = e; e = d.wrapping_add(t1); d = c; c = b; b = a; a = t1.wrapping_add(t2);
        }
        // round 29
        {
            let t1 = h.wrapping_add($crate::kernels::sha256::ep1(e)).wrapping_add($crate::kernels::sha256::ch(e, f, g)).wrapping_add(0xd5a79147u32.wrapping_add(ma29));
            let t2 = $crate::kernels::sha256::ep0(a).wrapping_add($crate::kernels::sha256::maj(a, b, c));
            h = g; g = f; f = e; e = d.wrapping_add(t1); d = c; c = b; b = a; a = t1.wrapping_add(t2);
        }
        // round 30
        {
            let t1 = h.wrapping_add($crate::kernels::sha256::ep1(e)).wrapping_add($crate::kernels::sha256::ch(e, f, g)).wrapping_add(0x06ca6351u32.wrapping_add(ma30));
            let t2 = $crate::kernels::sha256::ep0(a).wrapping_add($crate::kernels::sha256::maj(a, b, c));
            h = g; g = f; f = e; e = d.wrapping_add(t1); d = c; c = b; b = a; a = t1.wrapping_add(t2);
        }
        // round 31
        {
            let t1 = h.wrapping_add($crate::kernels::sha256::ep1(e)).wrapping_add($crate::kernels::sha256::ch(e, f, g)).wrapping_add(0x14292967u32.wrapping_add(ma31));
            let t2 = $crate::kernels::sha256::ep0(a).wrapping_add($crate::kernels::sha256::maj(a, b, c));
            h = g; g = f; f = e; e = d.wrapping_add(t1); d = c; c = b; b = a; a = t1.wrapping_add(t2);
        }
        // round 32
        {
            let t1 = h.wrapping_add($crate::kernels::sha256::ep1(e)).wrapping_add($crate::kernels::sha256::ch(e, f, g)).wrapping_add(0x27b70a85u32.wrapping_add(ma32));
            let t2 = $crate::kernels::sha256::ep0(a).wrapping_add($crate::kernels::sha256::maj(a, b, c));
            h = g; g = f; f = e; e = d.wrapping_add(t1); d = c; c = b; b = a; a = t1.wrapping_add(t2);
        }
        // round 33
        {
            let t1 = h.wrapping_add($crate::kernels::sha256::ep1(e)).wrapping_add($crate::kernels::sha256::ch(e, f, g)).wrapping_add(0x2e1b2138u32.wrapping_add(ma33));
            let t2 = $crate::kernels::sha256::ep0(a).wrapping_add($crate::kernels::sha256::maj(a, b, c));
            h = g; g = f; f = e; e = d.wrapping_add(t1); d = c; c = b; b = a; a = t1.wrapping_add(t2);
        }
        // round 34
        {
            let t1 = h.wrapping_add($crate::kernels::sha256::ep1(e)).wrapping_add($crate::kernels::sha256::ch(e, f, g)).wrapping_add(0x4d2c6dfcu32.wrapping_add(ma34));
            let t2 = $crate::kernels::sha256::ep0(a).wrapping_add($crate::kernels::sha256::maj(a, b, c));
            h = g; g = f; f = e; e = d.wrapping_add(t1); d = c; c = b; b = a; a = t1.wrapping_add(t2);
        }
        // round 35
        {
            let t1 = h.wrapping_add($crate::kernels::sha256::ep1(e)).wrapping_add($crate::kernels::sha256::ch(e, f, g)).wrapping_add(0x53380d13u32.wrapping_add(ma35));
            let t2 = $crate::kernels::sha256::ep0(a).wrapping_add($crate::kernels::sha256::maj(a, b, c));
            h = g; g = f; f = e; e = d.wrapping_add(t1); d = c; c = b; b = a; a = t1.wrapping_add(t2);
        }
        // round 36
        {
            let t1 = h.wrapping_add($crate::kernels::sha256::ep1(e)).wrapping_add($crate::kernels::sha256::ch(e, f, g)).wrapping_add(0x650a7354u32.wrapping_add(ma36));
            let t2 = $crate::kernels::sha256::ep0(a).wrapping_add($crate::kernels::sha256::maj(a, b, c));
            h = g; g = f; f = e; e = d.wrapping_add(t1); d = c; c = b; b = a; a = t1.wrapping_add(t2);
        }
        // round 37
        {
            let t1 = h.wrapping_add($crate::kernels::sha256::ep1(e)).wrapping_add($crate::kernels::sha256::ch(e, f, g)).wrapping_add(0x766a0abbu32.wrapping_add(ma37));
            let t2 = $crate::kernels::sha256::ep0(a).wrapping_add($crate::kernels::sha256::maj(a, b, c));
            h = g; g = f; f = e; e = d.wrapping_add(t1); d = c; c = b; b = a; a = t1.wrapping_add(t2);
        }
        // round 38
        {
            let t1 = h.wrapping_add($crate::kernels::sha256::ep1(e)).wrapping_add($crate::kernels::sha256::ch(e, f, g)).wrapping_add(0x81c2c92eu32.wrapping_add(ma38));
            let t2 = $crate::kernels::sha256::ep0(a).wrapping_add($crate::kernels::sha256::maj(a, b, c));
            h = g; g = f; f = e; e = d.wrapping_add(t1); d = c; c = b; b = a; a = t1.wrapping_add(t2);
        }
        // round 39
        {
            let t1 = h.wrapping_add($crate::kernels::sha256::ep1(e)).wrapping_add($crate::kernels::sha256::ch(e, f, g)).wrapping_add(0x92722c85u32.wrapping_add(ma39));
            let t2 = $crate::kernels::sha256::ep0(a).wrapping_add($crate::kernels::sha256::maj(a, b, c));
            h = g; g = f; f = e; e = d.wrapping_add(t1); d = c; c = b; b = a; a = t1.wrapping_add(t2);
        }
        // round 40
        {
            let t1 = h.wrapping_add($crate::kernels::sha256::ep1(e)).wrapping_add($crate::kernels::sha256::ch(e, f, g)).wrapping_add(0xa2bfe8a1u32.wrapping_add(ma40));
            let t2 = $crate::kernels::sha256::ep0(a).wrapping_add($crate::kernels::sha256::maj(a, b, c));
            h = g; g = f; f = e; e = d.wrapping_add(t1); d = c; c = b; b = a; a = t1.wrapping_add(t2);
        }
        // round 41
        {
            let t1 = h.wrapping_add($crate::kernels::sha256::ep1(e)).wrapping_add($crate::kernels::sha256::ch(e, f, g)).wrapping_add(0xa81a664bu32.wrapping_add(ma41));
            let t2 = $crate::kernels::sha256::ep0(a).wrapping_add($crate::kernels::sha256::maj(a, b, c));
            h = g; g = f; f = e; e = d.wrapping_add(t1); d = c; c = b; b = a; a = t1.wrapping_add(t2);
        }
        // round 42
        {
            let t1 = h.wrapping_add($crate::kernels::sha256::ep1(e)).wrapping_add($crate::kernels::sha256::ch(e, f, g)).wrapping_add(0xc24b8b70u32.wrapping_add(ma42));
            let t2 = $crate::kernels::sha256::ep0(a).wrapping_add($crate::kernels::sha256::maj(a, b, c));
            h = g; g = f; f = e; e = d.wrapping_add(t1); d = c; c = b; b = a; a = t1.wrapping_add(t2);
        }
        // round 43
        {
            let t1 = h.wrapping_add($crate::kernels::sha256::ep1(e)).wrapping_add($crate::kernels::sha256::ch(e, f, g)).wrapping_add(0xc76c51a3u32.wrapping_add(ma43));
            let t2 = $crate::kernels::sha256::ep0(a).wrapping_add($crate::kernels::sha256::maj(a, b, c));
            h = g; g = f; f = e; e = d.wrapping_add(t1); d = c; c = b; b = a; a = t1.wrapping_add(t2);
        }
        // round 44
        {
            let t1 = h.wrapping_add($crate::kernels::sha256::ep1(e)).wrapping_add($crate::kernels::sha256::ch(e, f, g)).wrapping_add(0xd192e819u32.wrapping_add(ma44));
            let t2 = $crate::kernels::sha256::ep0(a).wrapping_add($crate::kernels::sha256::maj(a, b, c));
            h = g; g = f; f = e; e = d.wrapping_add(t1); d = c; c = b; b = a; a = t1.wrapping_add(t2);
        }
        // round 45
        {
            let t1 = h.wrapping_add($crate::kernels::sha256::ep1(e)).wrapping_add($crate::kernels::sha256::ch(e, f, g)).wrapping_add(0xd6990624u32.wrapping_add(ma45));
            let t2 = $crate::kernels::sha256::ep0(a).wrapping_add($crate::kernels::sha256::maj(a, b, c));
            h = g; g = f; f = e; e = d.wrapping_add(t1); d = c; c = b; b = a; a = t1.wrapping_add(t2);
        }
        // round 46
        {
            let t1 = h.wrapping_add($crate::kernels::sha256::ep1(e)).wrapping_add($crate::kernels::sha256::ch(e, f, g)).wrapping_add(0xf40e3585u32.wrapping_add(ma46));
            let t2 = $crate::kernels::sha256::ep0(a).wrapping_add($crate::kernels::sha256::maj(a, b, c));
            h = g; g = f; f = e; e = d.wrapping_add(t1); d = c; c = b; b = a; a = t1.wrapping_add(t2);
        }
        // round 47
        {
            let t1 = h.wrapping_add($crate::kernels::sha256::ep1(e)).wrapping_add($crate::kernels::sha256::ch(e, f, g)).wrapping_add(0x106aa070u32.wrapping_add(ma47));
            let t2 = $crate::kernels::sha256::ep0(a).wrapping_add($crate::kernels::sha256::maj(a, b, c));
            h = g; g = f; f = e; e = d.wrapping_add(t1); d = c; c = b; b = a; a = t1.wrapping_add(t2);
        }
        // round 48
        {
            let t1 = h.wrapping_add($crate::kernels::sha256::ep1(e)).wrapping_add($crate::kernels::sha256::ch(e, f, g)).wrapping_add(0x19a4c116u32.wrapping_add(ma48));
            let t2 = $crate::kernels::sha256::ep0(a).wrapping_add($crate::kernels::sha256::maj(a, b, c));
            h = g; g = f; f = e; e = d.wrapping_add(t1); d = c; c = b; b = a; a = t1.wrapping_add(t2);
        }
        // round 49
        {
            let t1 = h.wrapping_add($crate::kernels::sha256::ep1(e)).wrapping_add($crate::kernels::sha256::ch(e, f, g)).wrapping_add(0x1e376c08u32.wrapping_add(ma49));
            let t2 = $crate::kernels::sha256::ep0(a).wrapping_add($crate::kernels::sha256::maj(a, b, c));
            h = g; g = f; f = e; e = d.wrapping_add(t1); d = c; c = b; b = a; a = t1.wrapping_add(t2);
        }
        // round 50
        {
            let t1 = h.wrapping_add($crate::kernels::sha256::ep1(e)).wrapping_add($crate::kernels::sha256::ch(e, f, g)).wrapping_add(0x2748774cu32.wrapping_add(ma50));
            let t2 = $crate::kernels::sha256::ep0(a).wrapping_add($crate::kernels::sha256::maj(a, b, c));
            h = g; g = f; f = e; e = d.wrapping_add(t1); d = c; c = b; b = a; a = t1.wrapping_add(t2);
        }
        // round 51
        {
            let t1 = h.wrapping_add($crate::kernels::sha256::ep1(e)).wrapping_add($crate::kernels::sha256::ch(e, f, g)).wrapping_add(0x34b0bcb5u32.wrapping_add(ma51));
            let t2 = $crate::kernels::sha256::ep0(a).wrapping_add($crate::kernels::sha256::maj(a, b, c));
            h = g; g = f; f = e; e = d.wrapping_add(t1); d = c; c = b; b = a; a = t1.wrapping_add(t2);
        }
        // round 52
        {
            let t1 = h.wrapping_add($crate::kernels::sha256::ep1(e)).wrapping_add($crate::kernels::sha256::ch(e, f, g)).wrapping_add(0x391c0cb3u32.wrapping_add(ma52));
            let t2 = $crate::kernels::sha256::ep0(a).wrapping_add($crate::kernels::sha256::maj(a, b, c));
            h = g; g = f; f = e; e = d.wrapping_add(t1); d = c; c = b; b = a; a = t1.wrapping_add(t2);
        }
        // round 53
        {
            let t1 = h.wrapping_add($crate::kernels::sha256::ep1(e)).wrapping_add($crate::kernels::sha256::ch(e, f, g)).wrapping_add(0x4ed8aa4au32.wrapping_add(ma53));
            let t2 = $crate::kernels::sha256::ep0(a).wrapping_add($crate::kernels::sha256::maj(a, b, c));
            h = g; g = f; f = e; e = d.wrapping_add(t1); d = c; c = b; b = a; a = t1.wrapping_add(t2);
        }
        // round 54
        {
            let t1 = h.wrapping_add($crate::kernels::sha256::ep1(e)).wrapping_add($crate::kernels::sha256::ch(e, f, g)).wrapping_add(0x5b9cca4fu32.wrapping_add(ma54));
            let t2 = $crate::kernels::sha256::ep0(a).wrapping_add($crate::kernels::sha256::maj(a, b, c));
            h = g; g = f; f = e; e = d.wrapping_add(t1); d = c; c = b; b = a; a = t1.wrapping_add(t2);
        }
        // round 55
        {
            let t1 = h.wrapping_add($crate::kernels::sha256::ep1(e)).wrapping_add($crate::kernels::sha256::ch(e, f, g)).wrapping_add(0x682e6ff3u32.wrapping_add(ma55));
            let t2 = $crate::kernels::sha256::ep0(a).wrapping_add($crate::kernels::sha256::maj(a, b, c));
            h = g; g = f; f = e; e = d.wrapping_add(t1); d = c; c = b; b = a; a = t1.wrapping_add(t2);
        }
        // round 56
        {
            let t1 = h.wrapping_add($crate::kernels::sha256::ep1(e)).wrapping_add($crate::kernels::sha256::ch(e, f, g)).wrapping_add(0x748f82eeu32.wrapping_add(ma56));
            let t2 = $crate::kernels::sha256::ep0(a).wrapping_add($crate::kernels::sha256::maj(a, b, c));
            h = g; g = f; f = e; e = d.wrapping_add(t1); d = c; c = b; b = a; a = t1.wrapping_add(t2);
        }
        // round 57
        {
            let t1 = h.wrapping_add($crate::kernels::sha256::ep1(e)).wrapping_add($crate::kernels::sha256::ch(e, f, g)).wrapping_add(0x78a5636fu32.wrapping_add(ma57));
            let t2 = $crate::kernels::sha256::ep0(a).wrapping_add($crate::kernels::sha256::maj(a, b, c));
            h = g; g = f; f = e; e = d.wrapping_add(t1); d = c; c = b; b = a; a = t1.wrapping_add(t2);
        }
        // round 58
        {
            let t1 = h.wrapping_add($crate::kernels::sha256::ep1(e)).wrapping_add($crate::kernels::sha256::ch(e, f, g)).wrapping_add(0x84c87814u32.wrapping_add(ma58));
            let t2 = $crate::kernels::sha256::ep0(a).wrapping_add($crate::kernels::sha256::maj(a, b, c));
            h = g; g = f; f = e; e = d.wrapping_add(t1); d = c; c = b; b = a; a = t1.wrapping_add(t2);
        }
        // round 59
        {
            let t1 = h.wrapping_add($crate::kernels::sha256::ep1(e)).wrapping_add($crate::kernels::sha256::ch(e, f, g)).wrapping_add(0x8cc70208u32.wrapping_add(ma59));
            let t2 = $crate::kernels::sha256::ep0(a).wrapping_add($crate::kernels::sha256::maj(a, b, c));
            h = g; g = f; f = e; e = d.wrapping_add(t1); d = c; c = b; b = a; a = t1.wrapping_add(t2);
        }
        // round 60
        {
            let t1 = h.wrapping_add($crate::kernels::sha256::ep1(e)).wrapping_add($crate::kernels::sha256::ch(e, f, g)).wrapping_add(0x90befffau32.wrapping_add(ma60));
            let t2 = $crate::kernels::sha256::ep0(a).wrapping_add($crate::kernels::sha256::maj(a, b, c));
            h = g; g = f; f = e; e = d.wrapping_add(t1); d = c; c = b; b = a; a = t1.wrapping_add(t2);
        }
        // round 61
        {
            let t1 = h.wrapping_add($crate::kernels::sha256::ep1(e)).wrapping_add($crate::kernels::sha256::ch(e, f, g)).wrapping_add(0xa4506cebu32.wrapping_add(ma61));
            let t2 = $crate::kernels::sha256::ep0(a).wrapping_add($crate::kernels::sha256::maj(a, b, c));
            h = g; g = f; f = e; e = d.wrapping_add(t1); d = c; c = b; b = a; a = t1.wrapping_add(t2);
        }
        // round 62
        {
            let t1 = h.wrapping_add($crate::kernels::sha256::ep1(e)).wrapping_add($crate::kernels::sha256::ch(e, f, g)).wrapping_add(0xbef9a3f7u32.wrapping_add(ma62));
            let t2 = $crate::kernels::sha256::ep0(a).wrapping_add($crate::kernels::sha256::maj(a, b, c));
            h = g; g = f; f = e; e = d.wrapping_add(t1); d = c; c = b; b = a; a = t1.wrapping_add(t2);
        }
        // round 63
        {
            let t1 = h.wrapping_add($crate::kernels::sha256::ep1(e)).wrapping_add($crate::kernels::sha256::ch(e, f, g)).wrapping_add(0xc67178f2u32.wrapping_add(ma63));
            let t2 = $crate::kernels::sha256::ep0(a).wrapping_add($crate::kernels::sha256::maj(a, b, c));
            h = g; g = f; f = e; e = d.wrapping_add(t1); d = c; c = b; b = a; a = t1.wrapping_add(t2);
        }
        let a0 = 0x6a09e667u32.wrapping_add(a);
        let a1 = 0xbb67ae85u32.wrapping_add(b);
        let a2 = 0x3c6ef372u32.wrapping_add(c);
        let a3 = 0xa54ff53au32.wrapping_add(d);
        let a4 = 0x510e527fu32.wrapping_add(e);
        let a5 = 0x9b05688cu32.wrapping_add(f);
        let a6 = 0x1f83d9abu32.wrapping_add(g);
        let a7 = 0x5be0cd19u32.wrapping_add(h);
        let mut a = a0;
        let mut b = a1;
        let mut c = a2;
        let mut d = a3;
        let mut e = a4;
        let mut f = a5;
        let mut g = a6;
        let mut h = a7;
        // round 0
        {
            let t1 = h.wrapping_add($crate::kernels::sha256::ep1(e)).wrapping_add($crate::kernels::sha256::ch(e, f, g)).wrapping_add(unsafe { $kw2[0] });
            let t2 = $crate::kernels::sha256::ep0(a).wrapping_add($crate::kernels::sha256::maj(a, b, c));
            h = g; g = f; f = e; e = d.wrapping_add(t1); d = c; c = b; b = a; a = t1.wrapping_add(t2);
        }
        // round 1
        {
            let t1 = h.wrapping_add($crate::kernels::sha256::ep1(e)).wrapping_add($crate::kernels::sha256::ch(e, f, g)).wrapping_add(unsafe { $kw2[1] });
            let t2 = $crate::kernels::sha256::ep0(a).wrapping_add($crate::kernels::sha256::maj(a, b, c));
            h = g; g = f; f = e; e = d.wrapping_add(t1); d = c; c = b; b = a; a = t1.wrapping_add(t2);
        }
        // round 2
        {
            let t1 = h.wrapping_add($crate::kernels::sha256::ep1(e)).wrapping_add($crate::kernels::sha256::ch(e, f, g)).wrapping_add(unsafe { $kw2[2] });
            let t2 = $crate::kernels::sha256::ep0(a).wrapping_add($crate::kernels::sha256::maj(a, b, c));
            h = g; g = f; f = e; e = d.wrapping_add(t1); d = c; c = b; b = a; a = t1.wrapping_add(t2);
        }
        // round 3
        {
            let t1 = h.wrapping_add($crate::kernels::sha256::ep1(e)).wrapping_add($crate::kernels::sha256::ch(e, f, g)).wrapping_add(unsafe { $kw2[3] });
            let t2 = $crate::kernels::sha256::ep0(a).wrapping_add($crate::kernels::sha256::maj(a, b, c));
            h = g; g = f; f = e; e = d.wrapping_add(t1); d = c; c = b; b = a; a = t1.wrapping_add(t2);
        }
        // round 4
        {
            let t1 = h.wrapping_add($crate::kernels::sha256::ep1(e)).wrapping_add($crate::kernels::sha256::ch(e, f, g)).wrapping_add(unsafe { $kw2[4] });
            let t2 = $crate::kernels::sha256::ep0(a).wrapping_add($crate::kernels::sha256::maj(a, b, c));
            h = g; g = f; f = e; e = d.wrapping_add(t1); d = c; c = b; b = a; a = t1.wrapping_add(t2);
        }
        // round 5
        {
            let t1 = h.wrapping_add($crate::kernels::sha256::ep1(e)).wrapping_add($crate::kernels::sha256::ch(e, f, g)).wrapping_add(unsafe { $kw2[5] });
            let t2 = $crate::kernels::sha256::ep0(a).wrapping_add($crate::kernels::sha256::maj(a, b, c));
            h = g; g = f; f = e; e = d.wrapping_add(t1); d = c; c = b; b = a; a = t1.wrapping_add(t2);
        }
        // round 6
        {
            let t1 = h.wrapping_add($crate::kernels::sha256::ep1(e)).wrapping_add($crate::kernels::sha256::ch(e, f, g)).wrapping_add(unsafe { $kw2[6] });
            let t2 = $crate::kernels::sha256::ep0(a).wrapping_add($crate::kernels::sha256::maj(a, b, c));
            h = g; g = f; f = e; e = d.wrapping_add(t1); d = c; c = b; b = a; a = t1.wrapping_add(t2);
        }
        // round 7
        {
            let t1 = h.wrapping_add($crate::kernels::sha256::ep1(e)).wrapping_add($crate::kernels::sha256::ch(e, f, g)).wrapping_add(unsafe { $kw2[7] });
            let t2 = $crate::kernels::sha256::ep0(a).wrapping_add($crate::kernels::sha256::maj(a, b, c));
            h = g; g = f; f = e; e = d.wrapping_add(t1); d = c; c = b; b = a; a = t1.wrapping_add(t2);
        }
        // round 8
        {
            let t1 = h.wrapping_add($crate::kernels::sha256::ep1(e)).wrapping_add($crate::kernels::sha256::ch(e, f, g)).wrapping_add(unsafe { $kw2[8] });
            let t2 = $crate::kernels::sha256::ep0(a).wrapping_add($crate::kernels::sha256::maj(a, b, c));
            h = g; g = f; f = e; e = d.wrapping_add(t1); d = c; c = b; b = a; a = t1.wrapping_add(t2);
        }
        // round 9
        {
            let t1 = h.wrapping_add($crate::kernels::sha256::ep1(e)).wrapping_add($crate::kernels::sha256::ch(e, f, g)).wrapping_add(unsafe { $kw2[9] });
            let t2 = $crate::kernels::sha256::ep0(a).wrapping_add($crate::kernels::sha256::maj(a, b, c));
            h = g; g = f; f = e; e = d.wrapping_add(t1); d = c; c = b; b = a; a = t1.wrapping_add(t2);
        }
        // round 10
        {
            let t1 = h.wrapping_add($crate::kernels::sha256::ep1(e)).wrapping_add($crate::kernels::sha256::ch(e, f, g)).wrapping_add(unsafe { $kw2[10] });
            let t2 = $crate::kernels::sha256::ep0(a).wrapping_add($crate::kernels::sha256::maj(a, b, c));
            h = g; g = f; f = e; e = d.wrapping_add(t1); d = c; c = b; b = a; a = t1.wrapping_add(t2);
        }
        // round 11
        {
            let t1 = h.wrapping_add($crate::kernels::sha256::ep1(e)).wrapping_add($crate::kernels::sha256::ch(e, f, g)).wrapping_add(unsafe { $kw2[11] });
            let t2 = $crate::kernels::sha256::ep0(a).wrapping_add($crate::kernels::sha256::maj(a, b, c));
            h = g; g = f; f = e; e = d.wrapping_add(t1); d = c; c = b; b = a; a = t1.wrapping_add(t2);
        }
        // round 12
        {
            let t1 = h.wrapping_add($crate::kernels::sha256::ep1(e)).wrapping_add($crate::kernels::sha256::ch(e, f, g)).wrapping_add(unsafe { $kw2[12] });
            let t2 = $crate::kernels::sha256::ep0(a).wrapping_add($crate::kernels::sha256::maj(a, b, c));
            h = g; g = f; f = e; e = d.wrapping_add(t1); d = c; c = b; b = a; a = t1.wrapping_add(t2);
        }
        // round 13
        {
            let t1 = h.wrapping_add($crate::kernels::sha256::ep1(e)).wrapping_add($crate::kernels::sha256::ch(e, f, g)).wrapping_add(unsafe { $kw2[13] });
            let t2 = $crate::kernels::sha256::ep0(a).wrapping_add($crate::kernels::sha256::maj(a, b, c));
            h = g; g = f; f = e; e = d.wrapping_add(t1); d = c; c = b; b = a; a = t1.wrapping_add(t2);
        }
        // round 14
        {
            let t1 = h.wrapping_add($crate::kernels::sha256::ep1(e)).wrapping_add($crate::kernels::sha256::ch(e, f, g)).wrapping_add(unsafe { $kw2[14] });
            let t2 = $crate::kernels::sha256::ep0(a).wrapping_add($crate::kernels::sha256::maj(a, b, c));
            h = g; g = f; f = e; e = d.wrapping_add(t1); d = c; c = b; b = a; a = t1.wrapping_add(t2);
        }
        // round 15
        {
            let t1 = h.wrapping_add($crate::kernels::sha256::ep1(e)).wrapping_add($crate::kernels::sha256::ch(e, f, g)).wrapping_add(unsafe { $kw2[15] });
            let t2 = $crate::kernels::sha256::ep0(a).wrapping_add($crate::kernels::sha256::maj(a, b, c));
            h = g; g = f; f = e; e = d.wrapping_add(t1); d = c; c = b; b = a; a = t1.wrapping_add(t2);
        }
        // round 16
        {
            let t1 = h.wrapping_add($crate::kernels::sha256::ep1(e)).wrapping_add($crate::kernels::sha256::ch(e, f, g)).wrapping_add(unsafe { $kw2[16] });
            let t2 = $crate::kernels::sha256::ep0(a).wrapping_add($crate::kernels::sha256::maj(a, b, c));
            h = g; g = f; f = e; e = d.wrapping_add(t1); d = c; c = b; b = a; a = t1.wrapping_add(t2);
        }
        // round 17
        {
            let t1 = h.wrapping_add($crate::kernels::sha256::ep1(e)).wrapping_add($crate::kernels::sha256::ch(e, f, g)).wrapping_add(unsafe { $kw2[17] });
            let t2 = $crate::kernels::sha256::ep0(a).wrapping_add($crate::kernels::sha256::maj(a, b, c));
            h = g; g = f; f = e; e = d.wrapping_add(t1); d = c; c = b; b = a; a = t1.wrapping_add(t2);
        }
        // round 18
        {
            let t1 = h.wrapping_add($crate::kernels::sha256::ep1(e)).wrapping_add($crate::kernels::sha256::ch(e, f, g)).wrapping_add(unsafe { $kw2[18] });
            let t2 = $crate::kernels::sha256::ep0(a).wrapping_add($crate::kernels::sha256::maj(a, b, c));
            h = g; g = f; f = e; e = d.wrapping_add(t1); d = c; c = b; b = a; a = t1.wrapping_add(t2);
        }
        // round 19
        {
            let t1 = h.wrapping_add($crate::kernels::sha256::ep1(e)).wrapping_add($crate::kernels::sha256::ch(e, f, g)).wrapping_add(unsafe { $kw2[19] });
            let t2 = $crate::kernels::sha256::ep0(a).wrapping_add($crate::kernels::sha256::maj(a, b, c));
            h = g; g = f; f = e; e = d.wrapping_add(t1); d = c; c = b; b = a; a = t1.wrapping_add(t2);
        }
        // round 20
        {
            let t1 = h.wrapping_add($crate::kernels::sha256::ep1(e)).wrapping_add($crate::kernels::sha256::ch(e, f, g)).wrapping_add(unsafe { $kw2[20] });
            let t2 = $crate::kernels::sha256::ep0(a).wrapping_add($crate::kernels::sha256::maj(a, b, c));
            h = g; g = f; f = e; e = d.wrapping_add(t1); d = c; c = b; b = a; a = t1.wrapping_add(t2);
        }
        // round 21
        {
            let t1 = h.wrapping_add($crate::kernels::sha256::ep1(e)).wrapping_add($crate::kernels::sha256::ch(e, f, g)).wrapping_add(unsafe { $kw2[21] });
            let t2 = $crate::kernels::sha256::ep0(a).wrapping_add($crate::kernels::sha256::maj(a, b, c));
            h = g; g = f; f = e; e = d.wrapping_add(t1); d = c; c = b; b = a; a = t1.wrapping_add(t2);
        }
        // round 22
        {
            let t1 = h.wrapping_add($crate::kernels::sha256::ep1(e)).wrapping_add($crate::kernels::sha256::ch(e, f, g)).wrapping_add(unsafe { $kw2[22] });
            let t2 = $crate::kernels::sha256::ep0(a).wrapping_add($crate::kernels::sha256::maj(a, b, c));
            h = g; g = f; f = e; e = d.wrapping_add(t1); d = c; c = b; b = a; a = t1.wrapping_add(t2);
        }
        // round 23
        {
            let t1 = h.wrapping_add($crate::kernels::sha256::ep1(e)).wrapping_add($crate::kernels::sha256::ch(e, f, g)).wrapping_add(unsafe { $kw2[23] });
            let t2 = $crate::kernels::sha256::ep0(a).wrapping_add($crate::kernels::sha256::maj(a, b, c));
            h = g; g = f; f = e; e = d.wrapping_add(t1); d = c; c = b; b = a; a = t1.wrapping_add(t2);
        }
        // round 24
        {
            let t1 = h.wrapping_add($crate::kernels::sha256::ep1(e)).wrapping_add($crate::kernels::sha256::ch(e, f, g)).wrapping_add(unsafe { $kw2[24] });
            let t2 = $crate::kernels::sha256::ep0(a).wrapping_add($crate::kernels::sha256::maj(a, b, c));
            h = g; g = f; f = e; e = d.wrapping_add(t1); d = c; c = b; b = a; a = t1.wrapping_add(t2);
        }
        // round 25
        {
            let t1 = h.wrapping_add($crate::kernels::sha256::ep1(e)).wrapping_add($crate::kernels::sha256::ch(e, f, g)).wrapping_add(unsafe { $kw2[25] });
            let t2 = $crate::kernels::sha256::ep0(a).wrapping_add($crate::kernels::sha256::maj(a, b, c));
            h = g; g = f; f = e; e = d.wrapping_add(t1); d = c; c = b; b = a; a = t1.wrapping_add(t2);
        }
        // round 26
        {
            let t1 = h.wrapping_add($crate::kernels::sha256::ep1(e)).wrapping_add($crate::kernels::sha256::ch(e, f, g)).wrapping_add(unsafe { $kw2[26] });
            let t2 = $crate::kernels::sha256::ep0(a).wrapping_add($crate::kernels::sha256::maj(a, b, c));
            h = g; g = f; f = e; e = d.wrapping_add(t1); d = c; c = b; b = a; a = t1.wrapping_add(t2);
        }
        // round 27
        {
            let t1 = h.wrapping_add($crate::kernels::sha256::ep1(e)).wrapping_add($crate::kernels::sha256::ch(e, f, g)).wrapping_add(unsafe { $kw2[27] });
            let t2 = $crate::kernels::sha256::ep0(a).wrapping_add($crate::kernels::sha256::maj(a, b, c));
            h = g; g = f; f = e; e = d.wrapping_add(t1); d = c; c = b; b = a; a = t1.wrapping_add(t2);
        }
        // round 28
        {
            let t1 = h.wrapping_add($crate::kernels::sha256::ep1(e)).wrapping_add($crate::kernels::sha256::ch(e, f, g)).wrapping_add(unsafe { $kw2[28] });
            let t2 = $crate::kernels::sha256::ep0(a).wrapping_add($crate::kernels::sha256::maj(a, b, c));
            h = g; g = f; f = e; e = d.wrapping_add(t1); d = c; c = b; b = a; a = t1.wrapping_add(t2);
        }
        // round 29
        {
            let t1 = h.wrapping_add($crate::kernels::sha256::ep1(e)).wrapping_add($crate::kernels::sha256::ch(e, f, g)).wrapping_add(unsafe { $kw2[29] });
            let t2 = $crate::kernels::sha256::ep0(a).wrapping_add($crate::kernels::sha256::maj(a, b, c));
            h = g; g = f; f = e; e = d.wrapping_add(t1); d = c; c = b; b = a; a = t1.wrapping_add(t2);
        }
        // round 30
        {
            let t1 = h.wrapping_add($crate::kernels::sha256::ep1(e)).wrapping_add($crate::kernels::sha256::ch(e, f, g)).wrapping_add(unsafe { $kw2[30] });
            let t2 = $crate::kernels::sha256::ep0(a).wrapping_add($crate::kernels::sha256::maj(a, b, c));
            h = g; g = f; f = e; e = d.wrapping_add(t1); d = c; c = b; b = a; a = t1.wrapping_add(t2);
        }
        // round 31
        {
            let t1 = h.wrapping_add($crate::kernels::sha256::ep1(e)).wrapping_add($crate::kernels::sha256::ch(e, f, g)).wrapping_add(unsafe { $kw2[31] });
            let t2 = $crate::kernels::sha256::ep0(a).wrapping_add($crate::kernels::sha256::maj(a, b, c));
            h = g; g = f; f = e; e = d.wrapping_add(t1); d = c; c = b; b = a; a = t1.wrapping_add(t2);
        }
        // round 32
        {
            let t1 = h.wrapping_add($crate::kernels::sha256::ep1(e)).wrapping_add($crate::kernels::sha256::ch(e, f, g)).wrapping_add(unsafe { $kw2[32] });
            let t2 = $crate::kernels::sha256::ep0(a).wrapping_add($crate::kernels::sha256::maj(a, b, c));
            h = g; g = f; f = e; e = d.wrapping_add(t1); d = c; c = b; b = a; a = t1.wrapping_add(t2);
        }
        // round 33
        {
            let t1 = h.wrapping_add($crate::kernels::sha256::ep1(e)).wrapping_add($crate::kernels::sha256::ch(e, f, g)).wrapping_add(unsafe { $kw2[33] });
            let t2 = $crate::kernels::sha256::ep0(a).wrapping_add($crate::kernels::sha256::maj(a, b, c));
            h = g; g = f; f = e; e = d.wrapping_add(t1); d = c; c = b; b = a; a = t1.wrapping_add(t2);
        }
        // round 34
        {
            let t1 = h.wrapping_add($crate::kernels::sha256::ep1(e)).wrapping_add($crate::kernels::sha256::ch(e, f, g)).wrapping_add(unsafe { $kw2[34] });
            let t2 = $crate::kernels::sha256::ep0(a).wrapping_add($crate::kernels::sha256::maj(a, b, c));
            h = g; g = f; f = e; e = d.wrapping_add(t1); d = c; c = b; b = a; a = t1.wrapping_add(t2);
        }
        // round 35
        {
            let t1 = h.wrapping_add($crate::kernels::sha256::ep1(e)).wrapping_add($crate::kernels::sha256::ch(e, f, g)).wrapping_add(unsafe { $kw2[35] });
            let t2 = $crate::kernels::sha256::ep0(a).wrapping_add($crate::kernels::sha256::maj(a, b, c));
            h = g; g = f; f = e; e = d.wrapping_add(t1); d = c; c = b; b = a; a = t1.wrapping_add(t2);
        }
        // round 36
        {
            let t1 = h.wrapping_add($crate::kernels::sha256::ep1(e)).wrapping_add($crate::kernels::sha256::ch(e, f, g)).wrapping_add(unsafe { $kw2[36] });
            let t2 = $crate::kernels::sha256::ep0(a).wrapping_add($crate::kernels::sha256::maj(a, b, c));
            h = g; g = f; f = e; e = d.wrapping_add(t1); d = c; c = b; b = a; a = t1.wrapping_add(t2);
        }
        // round 37
        {
            let t1 = h.wrapping_add($crate::kernels::sha256::ep1(e)).wrapping_add($crate::kernels::sha256::ch(e, f, g)).wrapping_add(unsafe { $kw2[37] });
            let t2 = $crate::kernels::sha256::ep0(a).wrapping_add($crate::kernels::sha256::maj(a, b, c));
            h = g; g = f; f = e; e = d.wrapping_add(t1); d = c; c = b; b = a; a = t1.wrapping_add(t2);
        }
        // round 38
        {
            let t1 = h.wrapping_add($crate::kernels::sha256::ep1(e)).wrapping_add($crate::kernels::sha256::ch(e, f, g)).wrapping_add(unsafe { $kw2[38] });
            let t2 = $crate::kernels::sha256::ep0(a).wrapping_add($crate::kernels::sha256::maj(a, b, c));
            h = g; g = f; f = e; e = d.wrapping_add(t1); d = c; c = b; b = a; a = t1.wrapping_add(t2);
        }
        // round 39
        {
            let t1 = h.wrapping_add($crate::kernels::sha256::ep1(e)).wrapping_add($crate::kernels::sha256::ch(e, f, g)).wrapping_add(unsafe { $kw2[39] });
            let t2 = $crate::kernels::sha256::ep0(a).wrapping_add($crate::kernels::sha256::maj(a, b, c));
            h = g; g = f; f = e; e = d.wrapping_add(t1); d = c; c = b; b = a; a = t1.wrapping_add(t2);
        }
        // round 40
        {
            let t1 = h.wrapping_add($crate::kernels::sha256::ep1(e)).wrapping_add($crate::kernels::sha256::ch(e, f, g)).wrapping_add(unsafe { $kw2[40] });
            let t2 = $crate::kernels::sha256::ep0(a).wrapping_add($crate::kernels::sha256::maj(a, b, c));
            h = g; g = f; f = e; e = d.wrapping_add(t1); d = c; c = b; b = a; a = t1.wrapping_add(t2);
        }
        // round 41
        {
            let t1 = h.wrapping_add($crate::kernels::sha256::ep1(e)).wrapping_add($crate::kernels::sha256::ch(e, f, g)).wrapping_add(unsafe { $kw2[41] });
            let t2 = $crate::kernels::sha256::ep0(a).wrapping_add($crate::kernels::sha256::maj(a, b, c));
            h = g; g = f; f = e; e = d.wrapping_add(t1); d = c; c = b; b = a; a = t1.wrapping_add(t2);
        }
        // round 42
        {
            let t1 = h.wrapping_add($crate::kernels::sha256::ep1(e)).wrapping_add($crate::kernels::sha256::ch(e, f, g)).wrapping_add(unsafe { $kw2[42] });
            let t2 = $crate::kernels::sha256::ep0(a).wrapping_add($crate::kernels::sha256::maj(a, b, c));
            h = g; g = f; f = e; e = d.wrapping_add(t1); d = c; c = b; b = a; a = t1.wrapping_add(t2);
        }
        // round 43
        {
            let t1 = h.wrapping_add($crate::kernels::sha256::ep1(e)).wrapping_add($crate::kernels::sha256::ch(e, f, g)).wrapping_add(unsafe { $kw2[43] });
            let t2 = $crate::kernels::sha256::ep0(a).wrapping_add($crate::kernels::sha256::maj(a, b, c));
            h = g; g = f; f = e; e = d.wrapping_add(t1); d = c; c = b; b = a; a = t1.wrapping_add(t2);
        }
        // round 44
        {
            let t1 = h.wrapping_add($crate::kernels::sha256::ep1(e)).wrapping_add($crate::kernels::sha256::ch(e, f, g)).wrapping_add(unsafe { $kw2[44] });
            let t2 = $crate::kernels::sha256::ep0(a).wrapping_add($crate::kernels::sha256::maj(a, b, c));
            h = g; g = f; f = e; e = d.wrapping_add(t1); d = c; c = b; b = a; a = t1.wrapping_add(t2);
        }
        // round 45
        {
            let t1 = h.wrapping_add($crate::kernels::sha256::ep1(e)).wrapping_add($crate::kernels::sha256::ch(e, f, g)).wrapping_add(unsafe { $kw2[45] });
            let t2 = $crate::kernels::sha256::ep0(a).wrapping_add($crate::kernels::sha256::maj(a, b, c));
            h = g; g = f; f = e; e = d.wrapping_add(t1); d = c; c = b; b = a; a = t1.wrapping_add(t2);
        }
        // round 46
        {
            let t1 = h.wrapping_add($crate::kernels::sha256::ep1(e)).wrapping_add($crate::kernels::sha256::ch(e, f, g)).wrapping_add(unsafe { $kw2[46] });
            let t2 = $crate::kernels::sha256::ep0(a).wrapping_add($crate::kernels::sha256::maj(a, b, c));
            h = g; g = f; f = e; e = d.wrapping_add(t1); d = c; c = b; b = a; a = t1.wrapping_add(t2);
        }
        // round 47
        {
            let t1 = h.wrapping_add($crate::kernels::sha256::ep1(e)).wrapping_add($crate::kernels::sha256::ch(e, f, g)).wrapping_add(unsafe { $kw2[47] });
            let t2 = $crate::kernels::sha256::ep0(a).wrapping_add($crate::kernels::sha256::maj(a, b, c));
            h = g; g = f; f = e; e = d.wrapping_add(t1); d = c; c = b; b = a; a = t1.wrapping_add(t2);
        }
        // round 48
        {
            let t1 = h.wrapping_add($crate::kernels::sha256::ep1(e)).wrapping_add($crate::kernels::sha256::ch(e, f, g)).wrapping_add(unsafe { $kw2[48] });
            let t2 = $crate::kernels::sha256::ep0(a).wrapping_add($crate::kernels::sha256::maj(a, b, c));
            h = g; g = f; f = e; e = d.wrapping_add(t1); d = c; c = b; b = a; a = t1.wrapping_add(t2);
        }
        // round 49
        {
            let t1 = h.wrapping_add($crate::kernels::sha256::ep1(e)).wrapping_add($crate::kernels::sha256::ch(e, f, g)).wrapping_add(unsafe { $kw2[49] });
            let t2 = $crate::kernels::sha256::ep0(a).wrapping_add($crate::kernels::sha256::maj(a, b, c));
            h = g; g = f; f = e; e = d.wrapping_add(t1); d = c; c = b; b = a; a = t1.wrapping_add(t2);
        }
        // round 50
        {
            let t1 = h.wrapping_add($crate::kernels::sha256::ep1(e)).wrapping_add($crate::kernels::sha256::ch(e, f, g)).wrapping_add(unsafe { $kw2[50] });
            let t2 = $crate::kernels::sha256::ep0(a).wrapping_add($crate::kernels::sha256::maj(a, b, c));
            h = g; g = f; f = e; e = d.wrapping_add(t1); d = c; c = b; b = a; a = t1.wrapping_add(t2);
        }
        // round 51
        {
            let t1 = h.wrapping_add($crate::kernels::sha256::ep1(e)).wrapping_add($crate::kernels::sha256::ch(e, f, g)).wrapping_add(unsafe { $kw2[51] });
            let t2 = $crate::kernels::sha256::ep0(a).wrapping_add($crate::kernels::sha256::maj(a, b, c));
            h = g; g = f; f = e; e = d.wrapping_add(t1); d = c; c = b; b = a; a = t1.wrapping_add(t2);
        }
        // round 52
        {
            let t1 = h.wrapping_add($crate::kernels::sha256::ep1(e)).wrapping_add($crate::kernels::sha256::ch(e, f, g)).wrapping_add(unsafe { $kw2[52] });
            let t2 = $crate::kernels::sha256::ep0(a).wrapping_add($crate::kernels::sha256::maj(a, b, c));
            h = g; g = f; f = e; e = d.wrapping_add(t1); d = c; c = b; b = a; a = t1.wrapping_add(t2);
        }
        // round 53
        {
            let t1 = h.wrapping_add($crate::kernels::sha256::ep1(e)).wrapping_add($crate::kernels::sha256::ch(e, f, g)).wrapping_add(unsafe { $kw2[53] });
            let t2 = $crate::kernels::sha256::ep0(a).wrapping_add($crate::kernels::sha256::maj(a, b, c));
            h = g; g = f; f = e; e = d.wrapping_add(t1); d = c; c = b; b = a; a = t1.wrapping_add(t2);
        }
        // round 54
        {
            let t1 = h.wrapping_add($crate::kernels::sha256::ep1(e)).wrapping_add($crate::kernels::sha256::ch(e, f, g)).wrapping_add(unsafe { $kw2[54] });
            let t2 = $crate::kernels::sha256::ep0(a).wrapping_add($crate::kernels::sha256::maj(a, b, c));
            h = g; g = f; f = e; e = d.wrapping_add(t1); d = c; c = b; b = a; a = t1.wrapping_add(t2);
        }
        // round 55
        {
            let t1 = h.wrapping_add($crate::kernels::sha256::ep1(e)).wrapping_add($crate::kernels::sha256::ch(e, f, g)).wrapping_add(unsafe { $kw2[55] });
            let t2 = $crate::kernels::sha256::ep0(a).wrapping_add($crate::kernels::sha256::maj(a, b, c));
            h = g; g = f; f = e; e = d.wrapping_add(t1); d = c; c = b; b = a; a = t1.wrapping_add(t2);
        }
        // round 56
        {
            let t1 = h.wrapping_add($crate::kernels::sha256::ep1(e)).wrapping_add($crate::kernels::sha256::ch(e, f, g)).wrapping_add(unsafe { $kw2[56] });
            let t2 = $crate::kernels::sha256::ep0(a).wrapping_add($crate::kernels::sha256::maj(a, b, c));
            h = g; g = f; f = e; e = d.wrapping_add(t1); d = c; c = b; b = a; a = t1.wrapping_add(t2);
        }
        // round 57
        {
            let t1 = h.wrapping_add($crate::kernels::sha256::ep1(e)).wrapping_add($crate::kernels::sha256::ch(e, f, g)).wrapping_add(unsafe { $kw2[57] });
            let t2 = $crate::kernels::sha256::ep0(a).wrapping_add($crate::kernels::sha256::maj(a, b, c));
            h = g; g = f; f = e; e = d.wrapping_add(t1); d = c; c = b; b = a; a = t1.wrapping_add(t2);
        }
        // round 58
        {
            let t1 = h.wrapping_add($crate::kernels::sha256::ep1(e)).wrapping_add($crate::kernels::sha256::ch(e, f, g)).wrapping_add(unsafe { $kw2[58] });
            let t2 = $crate::kernels::sha256::ep0(a).wrapping_add($crate::kernels::sha256::maj(a, b, c));
            h = g; g = f; f = e; e = d.wrapping_add(t1); d = c; c = b; b = a; a = t1.wrapping_add(t2);
        }
        // round 59
        {
            let t1 = h.wrapping_add($crate::kernels::sha256::ep1(e)).wrapping_add($crate::kernels::sha256::ch(e, f, g)).wrapping_add(unsafe { $kw2[59] });
            let t2 = $crate::kernels::sha256::ep0(a).wrapping_add($crate::kernels::sha256::maj(a, b, c));
            h = g; g = f; f = e; e = d.wrapping_add(t1); d = c; c = b; b = a; a = t1.wrapping_add(t2);
        }
        // round 60
        {
            let t1 = h.wrapping_add($crate::kernels::sha256::ep1(e)).wrapping_add($crate::kernels::sha256::ch(e, f, g)).wrapping_add(unsafe { $kw2[60] });
            let t2 = $crate::kernels::sha256::ep0(a).wrapping_add($crate::kernels::sha256::maj(a, b, c));
            h = g; g = f; f = e; e = d.wrapping_add(t1); d = c; c = b; b = a; a = t1.wrapping_add(t2);
        }
        // round 61
        {
            let t1 = h.wrapping_add($crate::kernels::sha256::ep1(e)).wrapping_add($crate::kernels::sha256::ch(e, f, g)).wrapping_add(unsafe { $kw2[61] });
            let t2 = $crate::kernels::sha256::ep0(a).wrapping_add($crate::kernels::sha256::maj(a, b, c));
            h = g; g = f; f = e; e = d.wrapping_add(t1); d = c; c = b; b = a; a = t1.wrapping_add(t2);
        }
        // round 62
        {
            let t1 = h.wrapping_add($crate::kernels::sha256::ep1(e)).wrapping_add($crate::kernels::sha256::ch(e, f, g)).wrapping_add(unsafe { $kw2[62] });
            let t2 = $crate::kernels::sha256::ep0(a).wrapping_add($crate::kernels::sha256::maj(a, b, c));
            h = g; g = f; f = e; e = d.wrapping_add(t1); d = c; c = b; b = a; a = t1.wrapping_add(t2);
        }
        // round 63
        {
            let t1 = h.wrapping_add($crate::kernels::sha256::ep1(e)).wrapping_add($crate::kernels::sha256::ch(e, f, g)).wrapping_add(unsafe { $kw2[63] });
            let t2 = $crate::kernels::sha256::ep0(a).wrapping_add($crate::kernels::sha256::maj(a, b, c));
            h = g; g = f; f = e; e = d.wrapping_add(t1); d = c; c = b; b = a; a = t1.wrapping_add(t2);
        }
        let b0 = a0.wrapping_add(a);
        let b1 = a1.wrapping_add(b);
        let b2 = a2.wrapping_add(c);
        let b3 = a3.wrapping_add(d);
        let b4 = a4.wrapping_add(e);
        let b5 = a5.wrapping_add(f);
        let b6 = a6.wrapping_add(g);
        let b7 = a7.wrapping_add(h);
        let $h0 = b0;
        let $h1 = b1;
        let $h2 = b2;
        let $h3 = b3;
        let $h4 = b4;
        let $h5 = b5;
        let $h6 = b6;
        let $h7 = b7;
    };
}

