#!/usr/bin/env python3
"""Generates src/kernels/base58.rs as a `base58_chunks!` macro that produces
the 9 base-58^5 carry-propagated chunks (each 0..58^5-1) directly into
caller-named u32 locals.

We deliberately stop *before* digit decomposition and ASCII conversion. The
match in vanity_search runs in numeric digit space, so:
  - we never materialize the 45-digit `raw_base58` array (kills 45 local-mem
    stores + 44 runtime-indexed local-mem loads),
  - we never call `alphabet_at` (kills the residual `call.uni` and ~44 calls
    per inner-loop iter),
  - we only decompose the chunks the prefix/suffix actually touch (top two
    chunks for prefix, bottom two for suffix), and we do that with constant-
    index arithmetic so it stays in registers.

Output to stdout — redirect to src/kernels/base58.rs."""

ENC_TABLE = [
    [513735,    77223048,  437087610, 300156666, 605448490, 214625350, 141436834, 379377856],
    [0,         78508,     646269101, 118408823, 91512303,  209184527, 413102373, 153715680],
    [0,         0,         11997,     486083817, 3737691,   294005210, 247894721, 289024608],
    [0,         0,         0,         1833,      324463681, 385795061, 551597588, 21339008],
    [0,         0,         0,         0,         280,       127692781, 389432875, 357132832],
    [0,         0,         0,         0,         0,         42,        537767569, 410450016],
    [0,         0,         0,         0,         0,         0,         6,         356826688],
    [0,         0,         0,         0,         0,         0,         0,         1],
]

print("""// AUTOGENERATED by scripts/gen_bs58.py — do not edit by hand.

// 58^5 — the base of each carry-propagated chunk.
pub(crate) const R1: u64 = 656356768;

/// Convert a 32-byte big-endian integer (passed as 8 u32s in big-endian
/// order: $b0 is the high word) into 9 base-58^5 chunks, with carry already
/// propagated. The chunks $c7_0..$c0_8 are injected as `let` bindings into
/// the caller's scope, each in [0, 58^5).
///
/// Layout of the implied 45 base58 digits, in order (digit 0 is highest):
///   $c7_0 → digits 0..5       (digit 0 always 0 for any 32-byte input)
///   $c7_1 → digits 5..10
///   $c6_2 → digits 10..15
///   $c5_3 → digits 15..20
///   $c4_4 → digits 20..25
///   $c3_5 → digits 25..30
///   $c2_6 → digits 30..35
///   $c1_7 → digits 35..40
///   $c0_8 → digits 40..45
///
/// To extract digit i (0..45) of chunk c:
///   digit_i = (c / DIVISORS[i % 5]) % 58
///   where DIVISORS = [11316496, 195112, 3364, 58, 1]  // 58^4..58^0
#[macro_export]
macro_rules! base58_chunks {
    ($b0:expr, $b1:expr, $b2:expr, $b3:expr,
     $b4:expr, $b5:expr, $b6:expr, $b7:expr,
     $c7_0:ident, $c7_1:ident, $c6_2:ident, $c5_3:ident, $c4_4:ident,
     $c3_5:ident, $c2_6:ident, $c1_7:ident, $c0_8:ident) => {
        let bin0: u32 = $b0;
        let bin1: u32 = $b1;
        let bin2: u32 = $b2;
        let bin3: u32 = $b3;
        let bin4: u32 = $b4;
        let bin5: u32 = $b5;
        let bin6: u32 = $b6;
        let bin7: u32 = $b7;

        // base-58^5 multiply-accumulates (compile-time-constant table inlined).
        let im0: u64 = 0;
""")

for k in range(1, 9):
    j = k - 1
    terms = []
    for i_row in range(8):
        coeff = ENC_TABLE[i_row][j]
        if coeff != 0:
            terms.append(f"bin{i_row} as u64 * {coeff}u64")
    if terms:
        expr = " + ".join(terms)
        print(f"        let im{k}: u64 = {expr};")
    else:
        print(f"        let im{k}: u64 = 0;")

print("""
        // carry propagation: chunks ripple from low (im8) to high (im0).
        const __R1: u64 = $crate::kernels::base58::R1;
""")

prev = [f"im{k}" for k in range(9)]
cur = list(prev)
for step, i in enumerate(reversed(range(1, 9))):
    cur[i-1] = f"k{step}_{i-1}"
    cur[i] = f"k{step}_{i}"
    print(f"        let {cur[i-1]}: u64 = {prev[i-1]} + ({prev[i]} / __R1);")
    print(f"        let {cur[i]}: u64 = {prev[i]} % __R1;")
    prev = list(cur)

# prev[0..9] now hold the 9 final chunks: prev[0]=c7_0, prev[1]=c7_1,
# prev[2]=c6_2, ..., prev[8]=c0_8.
final = list(prev)

print(f"""
        // inject as caller-named u32 locals (each fits in u32 since R1 < 2^30).
        let $c7_0: u32 = {final[0]} as u32;
        let $c7_1: u32 = {final[1]} as u32;
        let $c6_2: u32 = {final[2]} as u32;
        let $c5_3: u32 = {final[3]} as u32;
        let $c4_4: u32 = {final[4]} as u32;
        let $c3_5: u32 = {final[5]} as u32;
        let $c2_6: u32 = {final[6]} as u32;
        let $c1_7: u32 = {final[7]} as u32;
        let $c0_8: u32 = {final[8]} as u32;
    }};
}}
""")
