#!/usr/bin/env python3
"""Generates src/kernels/sha256.rs as a pair of macros:

  sha256_80!(base, seed, owner => h0, h1, h2, h3, h4, h5, h6, h7)

      Hash 80 bytes (base[32] || seed[16] || owner[32]) and *inject* the 8 u32
      result words as `let h0 = ...; ... let h7 = ...;` into the caller's scope.
      This keeps the digest in registers — no [u8;32] buffer ever exists, so we
      don't pay local-memory traffic between sha256 and the next stage.

  sha256_transform!(state, block)
      Compatibility wrapper around the same compress core, used by hostside
      tests. Operates on byte-array I/O and is therefore slower; not used in
      the hot path.

Output to stdout — redirect to src/kernels/sha256.rs."""

K = [
    0x428a2f98, 0x71374491, 0xb5c0fbcf, 0xe9b5dba5, 0x3956c25b, 0x59f111f1, 0x923f82a4, 0xab1c5ed5,
    0xd807aa98, 0x12835b01, 0x243185be, 0x550c7dc3, 0x72be5d74, 0x80deb1fe, 0x9bdc06a7, 0xc19bf174,
    0xe49b69c1, 0xefbe4786, 0x0fc19dc6, 0x240ca1cc, 0x2de92c6f, 0x4a7484aa, 0x5cb0a9dc, 0x76f988da,
    0x983e5152, 0xa831c66d, 0xb00327c8, 0xbf597fc7, 0xc6e00bf3, 0xd5a79147, 0x06ca6351, 0x14292967,
    0x27b70a85, 0x2e1b2138, 0x4d2c6dfc, 0x53380d13, 0x650a7354, 0x766a0abb, 0x81c2c92e, 0x92722c85,
    0xa2bfe8a1, 0xa81a664b, 0xc24b8b70, 0xc76c51a3, 0xd192e819, 0xd6990624, 0xf40e3585, 0x106aa070,
    0x19a4c116, 0x1e376c08, 0x2748774c, 0x34b0bcb5, 0x391c0cb3, 0x4ed8aa4a, 0x5b9cca4f, 0x682e6ff3,
    0x748f82ee, 0x78a5636f, 0x84c87814, 0x8cc70208, 0x90befffa, 0xa4506ceb, 0xbef9a3f7, 0xc67178f2,
]

INIT_STATE = [0x6a09e667, 0xbb67ae85, 0x3c6ef372, 0xa54ff53a,
              0x510e527f, 0x9b05688c, 0x1f83d9ab, 0x5be0cd19]


# Helper-function paths used inside the emitted macro body.
EP0 = "$crate::kernels::sha256::ep0"
EP1 = "$crate::kernels::sha256::ep1"
SIG0 = "$crate::kernels::sha256::sig0"
SIG1 = "$crate::kernels::sha256::sig1"
CH = "$crate::kernels::sha256::ch"
MAJ = "$crate::kernels::sha256::maj"


def emit_load_m(prefix, byte_expr_for_idx, indent):
    for i in range(16):
        b0, b1, b2, b3 = i*4, i*4+1, i*4+2, i*4+3
        print(f"{indent}let m{prefix}{i:02}: u32 =")
        print(f"{indent}      (({byte_expr_for_idx(b0)}) as u32) << 24")
        print(f"{indent}    | (({byte_expr_for_idx(b1)}) as u32) << 16")
        print(f"{indent}    | (({byte_expr_for_idx(b2)}) as u32) << 8")
        print(f"{indent}    | (({byte_expr_for_idx(b3)}) as u32);")


def emit_extend_m(prefix, indent):
    for i in range(16, 64):
        print(f"{indent}let m{prefix}{i:02}: u32 = "
              f"{SIG1}(m{prefix}{i-2:02})"
              f".wrapping_add(m{prefix}{i-7:02})"
              f".wrapping_add({SIG0}(m{prefix}{i-15:02}))"
              f".wrapping_add(m{prefix}{i-16:02});")


def emit_compress(prefix, in_state_vars, out_state_vars, indent):
    a, b, c, d, e, f, g, h = in_state_vars
    print(f"{indent}let mut a = {a};")
    print(f"{indent}let mut b = {b};")
    print(f"{indent}let mut c = {c};")
    print(f"{indent}let mut d = {d};")
    print(f"{indent}let mut e = {e};")
    print(f"{indent}let mut f = {f};")
    print(f"{indent}let mut g = {g};")
    print(f"{indent}let mut h = {h};")
    for i in range(64):
        print(f"{indent}// round {i}")
        print(f"{indent}{{")
        print(f"{indent}    let t1 = h.wrapping_add({EP1}(e)).wrapping_add({CH}(e, f, g))"
              f".wrapping_add(0x{K[i]:08x}u32).wrapping_add(m{prefix}{i:02});")
        print(f"{indent}    let t2 = {EP0}(a).wrapping_add({MAJ}(a, b, c));")
        print(f"{indent}    h = g; g = f; f = e; e = d.wrapping_add(t1); "
              f"d = c; c = b; b = a; a = t1.wrapping_add(t2);")
        print(f"{indent}}}")
    oa, ob, oc, od, oe, of, og, oh = out_state_vars
    print(f"{indent}let {oa} = {a}.wrapping_add(a);")
    print(f"{indent}let {ob} = {b}.wrapping_add(b);")
    print(f"{indent}let {oc} = {c}.wrapping_add(c);")
    print(f"{indent}let {od} = {d}.wrapping_add(d);")
    print(f"{indent}let {oe} = {e}.wrapping_add(e);")
    print(f"{indent}let {of} = {f}.wrapping_add(f);")
    print(f"{indent}let {og} = {g}.wrapping_add(g);")
    print(f"{indent}let {oh} = {h}.wrapping_add(h);")


# ─── header ─────────────────────────────────────────────────────────────────
print("""// AUTOGENERATED by scripts/gen_sha.py — do not edit by hand.

// Small inline helpers. Emitted as `pub(crate) fn #[inline(always)]` because
// they're tiny (3-5 ops) and rustc's MIR inliner folds them into the caller
// before cuda-oxide's collector ever sees them as standalone items —
// confirmed: no `vanity__kernels__sha256__ep0` etc. in the emitted PTX.

#[inline(always)]
pub(crate) fn ep0(x: u32) -> u32 { x.rotate_right(2) ^ x.rotate_right(13) ^ x.rotate_right(22) }
#[inline(always)]
pub(crate) fn ep1(x: u32) -> u32 { x.rotate_right(6) ^ x.rotate_right(11) ^ x.rotate_right(25) }
#[inline(always)]
pub(crate) fn sig0(x: u32) -> u32 { x.rotate_right(7) ^ x.rotate_right(18) ^ (x >> 3) }
#[inline(always)]
pub(crate) fn sig1(x: u32) -> u32 { x.rotate_right(17) ^ x.rotate_right(19) ^ (x >> 10) }
#[inline(always)]
pub(crate) fn ch(x: u32, y: u32, z: u32) -> u32 { (x & y) ^ (!x & z) }
#[inline(always)]
pub(crate) fn maj(x: u32, y: u32, z: u32) -> u32 { (x & y) ^ (x & z) ^ (y & z) }

/// Hash base[32] || seed[16] || owner[32] (80 bytes) and inject the 8 u32
/// result words as named `let` bindings into the caller's scope.
///
/// Why a macro and not a fn: cuda-oxide alpha drops `#[inline(always)]` on
/// larger fns, leaving them as PTX `call.uni`s. That kills the surrounding
/// loop-invariant motion (base/owner constants can't be hoisted out of the
/// kernel's main loop) and forces the digest through a stack [u8;32]. As a
/// macro the entire compress + final add lives in the kernel's MIR, so the
/// 8 u32 outputs stay in registers all the way to the next stage.
///
/// The seed is taken as 4 u32s (big-endian-packed bytes 0..4, 4..8, 8..12,
/// 12..16) instead of `&[u8;16]` so the caller doesn't have to materialise
/// the seed in local memory — it can live entirely in registers between the
/// PRNG draws and the SHA compress.
///
/// Args:
///   $base   : &[u8; 32]
///   $s0..$s3: u32 — seed bytes 0..16 BE-packed (s0 holds bytes 0..4)
///   $owner  : &[u8; 32]
///   $h0..$h7: ident — caller-named locals to receive the digest words (BE).
#[macro_export]
macro_rules! sha256_80 {
    ($base:expr,
     $s0:expr, $s1:expr, $s2:expr, $s3:expr,
     $owner:expr,
     $h0:ident, $h1:ident, $h2:ident, $h3:ident,
     $h4:ident, $h5:ident, $h6:ident, $h7:ident) => {
        let __base: &[u8; 32] = $base;
        let __owner: &[u8; 32] = $owner;
        let __seed_w0: u32 = $s0;
        let __seed_w1: u32 = $s1;
        let __seed_w2: u32 = $s2;
        let __seed_w3: u32 = $s3;
        let bp = __base.as_ptr();
        let op = __owner.as_ptr();
""")

# ─── block 0: bytes 0..32 = base, 32..48 = seed (4 u32s), 48..64 = owner[0..16]
# We bypass byte-loading for the seed entirely: the SHA message words ma08..ma11
# are exactly the 4 BE-packed u32s the caller passed in, so we emit those directly
# and skip the per-byte load+shift dance for the seed slot.
def block0_byte(b):
    if b < 32:
        return f"unsafe {{ *bp.add({b}) }}"
    elif b < 48:
        # seed bytes — handled by direct ma assignment below; this path
        # would only fire for a leftover byte expression and is never used.
        raise AssertionError(f"seed byte {b} should not be loaded byte-wise")
    else:
        return f"unsafe {{ *op.add({b - 48}) }}"

# Emit ma00..ma07 (base) and ma12..ma15 (owner[0..16]) via byte loads, but
# splice in ma08..ma11 = seed words directly.
def emit_load_m_block0_with_seed(indent):
    for i in range(16):
        if 8 <= i <= 11:
            print(f"{indent}let ma{i:02}: u32 = __seed_w{i - 8};")
            continue
        b0, b1, b2, b3 = i*4, i*4+1, i*4+2, i*4+3
        print(f"{indent}let ma{i:02}: u32 =")
        print(f"{indent}      (({block0_byte(b0)}) as u32) << 24")
        print(f"{indent}    | (({block0_byte(b1)}) as u32) << 16")
        print(f"{indent}    | (({block0_byte(b2)}) as u32) << 8")
        print(f"{indent}    | (({block0_byte(b3)}) as u32);")

emit_load_m_block0_with_seed(indent="        ")
emit_extend_m("a", indent="        ")

in_state_a = tuple(f"0x{INIT_STATE[i]:08x}u32" for i in range(8))
out_state_a = ("a0", "a1", "a2", "a3", "a4", "a5", "a6", "a7")
emit_compress("a", in_state_a, out_state_a, indent="        ")

# ─── block 1: owner[16..32] || 0x80 || zeros... || bitlen_be(640) ───────────
BITLEN_BYTES = [0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0x80]
def block1_byte(b):
    if b < 16:
        return f"unsafe {{ *op.add({b + 16}) }}"
    elif b == 16:
        return "0x80u8"
    elif b < 56:
        return "0u8"
    else:
        return f"0x{BITLEN_BYTES[b - 56]:02x}u8"

emit_load_m("b", block1_byte, indent="        ")
emit_extend_m("b", indent="        ")

in_state_b = ("a0", "a1", "a2", "a3", "a4", "a5", "a6", "a7")
out_state_b = ("b0", "b1", "b2", "b3", "b4", "b5", "b6", "b7")
emit_compress("b", in_state_b, out_state_b, indent="        ")

# ─── inject named outputs ───────────────────────────────────────────────────
print("""        let $h0 = b0;
        let $h1 = b1;
        let $h2 = b2;
        let $h3 = b3;
        let $h4 = b4;
        let $h5 = b5;
        let $h6 = b6;
        let $h7 = b7;
    };
}
""")
