#!/usr/bin/env python3
"""Generates src/kernels/sha256.rs:

  sha256_80!(base, seed, owner => h0, h1, h2, h3, h4, h5, h6, h7)

      Hash 80 bytes (base[32] || seed[16] || owner[32]) and *inject* the 8 u32
      result words as `let h0 = ...; ... let h7 = ...;` into the caller's scope.
      This keeps the digest in registers — no [u8;32] buffer ever exists, so we
      don't pay local-memory traffic between sha256 and the next stage.

Output to stdout — redirect to src/kernels/sha256.rs."""

K = [
    0x428a2f98, 0x71374491, 0xb5c0fbcf, 0xe9b5dba5, 0x3956c25b, 0x59f111f1, 0x923f82a4, 0xab1c5ed5,
    0xd807aa98, 0x12835b01, 0x243185be, 0x550c7dc3, 0x72be5d74, 0x80deb1fe, 0x9bdc06a7, 0xc19bf174,
    0xe49b69c1, 0xefbe4786, 0x0fc19dc6, 0x240ca1cc, 0x2de92c6f, 0x4a7484aa, 0x5cb0a9dc, 0x76f988da,
    0x983e5152, 0xa831c66d, 0xb00327c8, 0xbf597fc7, 0xc6e00bf3, 0xd5a79147, 0x06ca6351, 0x14292967,
    0x27b70a85, 0x2e1b2138, 0x4d2c6dfc, 0x53380d13, 0x650a7354, 0x766a0abb, 0x81c2c92e, 0x92722c85,
    0xa2bfe8a1, 0xa81a664b, 0xc24b8b70, 0xc76c51a3, 0xd192e819, 0xd6990624, 0xf40e3585, 0x106aa070,
    0x19a4c116, 0x1e376c08, 0x2748774c, 0x34b0bcb5, 0x391c0cb3, 0x4ed8aa4a, 0x5b9cca4f, 0x682e6ff3,
    0x748f82ee, 0x78a5636f, 0x84c87814, 0x8cc70208, 0x90befffa, 0xa4506ceb, 0xbef9a3f7, 0xc67178f2,
]

INIT_STATE = [0x6a09e667, 0xbb67ae85, 0x3c6ef372, 0xa54ff53a,
              0x510e527f, 0x9b05688c, 0x1f83d9ab, 0x5be0cd19]


# Helper-function paths used inside the emitted macro body.
EP0 = "$crate::kernels::sha256::ep0"
EP1 = "$crate::kernels::sha256::ep1"
SIG0 = "$crate::kernels::sha256::sig0"
SIG1 = "$crate::kernels::sha256::sig1"
CH = "$crate::kernels::sha256::ch"
MAJ = "$crate::kernels::sha256::maj"


def emit_load_m(prefix, byte_expr_for_idx, indent):
    for i in range(16):
        b0, b1, b2, b3 = i*4, i*4+1, i*4+2, i*4+3
        print(f"{indent}let m{prefix}{i:02}: u32 =")
        print(f"{indent}      (({byte_expr_for_idx(b0)}) as u32) << 24")
        print(f"{indent}    | (({byte_expr_for_idx(b1)}) as u32) << 16")
        print(f"{indent}    | (({byte_expr_for_idx(b2)}) as u32) << 8")
        print(f"{indent}    | (({byte_expr_for_idx(b3)}) as u32);")


def emit_extend_m(prefix, indent):
    for i in range(16, 64):
        print(f"{indent}let m{prefix}{i:02}: u32 = "
              f"{SIG1}(m{prefix}{i-2:02})"
              f".wrapping_add(m{prefix}{i-7:02})"
              f".wrapping_add({SIG0}(m{prefix}{i-15:02}))"
              f".wrapping_add(m{prefix}{i-16:02});")


def emit_compress(prefix, init_vars, addback_vars, out_state_vars, indent, start_round=0):
    """Emit the 64-round compression body.

    init_vars   : 8-tuple — values to init a..h at round `start_round`.
                  When start_round > 0 this should be the host-precomputed
                  state after rounds 0..start_round-1 (the "midstate").
    addback_vars: 8-tuple — values added back to post-compress a..h. Per the
                  SHA spec this is the original IV (or block's state-in),
                  NOT init_vars — the midstate optimisation lifts init_vars
                  but the canonical add-back still uses the IV.
    """
    a, b, c, d, e, f, g, h = init_vars
    print(f"{indent}let mut a = {a};")
    print(f"{indent}let mut b = {b};")
    print(f"{indent}let mut c = {c};")
    print(f"{indent}let mut d = {d};")
    print(f"{indent}let mut e = {e};")
    print(f"{indent}let mut f = {f};")
    print(f"{indent}let mut g = {g};")
    print(f"{indent}let mut h = {h};")
    for i in range(start_round, 64):
        print(f"{indent}// round {i}")
        print(f"{indent}{{")
        print(f"{indent}    let t1 = h.wrapping_add({EP1}(e)).wrapping_add({CH}(e, f, g))"
              f".wrapping_add(0x{K[i]:08x}u32).wrapping_add(m{prefix}{i:02});")
        print(f"{indent}    let t2 = {EP0}(a).wrapping_add({MAJ}(a, b, c));")
        print(f"{indent}    h = g; g = f; f = e; e = d.wrapping_add(t1); "
              f"d = c; c = b; b = a; a = t1.wrapping_add(t2);")
        print(f"{indent}}}")
    oa, ob, oc, od, oe, of, og, oh = out_state_vars
    aa, ab, ac, ad, ae, af, ag, ah = addback_vars
    print(f"{indent}let {oa} = {aa}.wrapping_add(a);")
    print(f"{indent}let {ob} = {ab}.wrapping_add(b);")
    print(f"{indent}let {oc} = {ac}.wrapping_add(c);")
    print(f"{indent}let {od} = {ad}.wrapping_add(d);")
    print(f"{indent}let {oe} = {ae}.wrapping_add(e);")
    print(f"{indent}let {of} = {af}.wrapping_add(f);")
    print(f"{indent}let {og} = {ag}.wrapping_add(g);")
    print(f"{indent}let {oh} = {ah}.wrapping_add(h);")


# ─── header ─────────────────────────────────────────────────────────────────
print("""// AUTOGENERATED by scripts/gen_sha.py — do not edit by hand.

// Small inline helpers. Emitted as `pub(crate) fn #[inline(always)]` because
// they're tiny (3-5 ops) and rustc's MIR inliner folds them into the caller
// before cuda-oxide's collector ever sees them as standalone items —
// confirmed: no `vanity__kernels__sha256__ep0` etc. in the emitted PTX.

#[inline(always)]
pub(crate) fn ep0(x: u32) -> u32 { x.rotate_right(2) ^ x.rotate_right(13) ^ x.rotate_right(22) }
#[inline(always)]
pub(crate) fn ep1(x: u32) -> u32 { x.rotate_right(6) ^ x.rotate_right(11) ^ x.rotate_right(25) }
#[inline(always)]
pub(crate) fn sig0(x: u32) -> u32 { x.rotate_right(7) ^ x.rotate_right(18) ^ (x >> 3) }
#[inline(always)]
pub(crate) fn sig1(x: u32) -> u32 { x.rotate_right(17) ^ x.rotate_right(19) ^ (x >> 10) }
#[inline(always)]
pub(crate) fn ch(x: u32, y: u32, z: u32) -> u32 { (x & y) ^ (!x & z) }
#[inline(always)]
pub(crate) fn maj(x: u32, y: u32, z: u32) -> u32 { (x & y) ^ (x & z) ^ (y & z) }

/// Hash base[32] || seed[16] || owner[32] (80 bytes) and inject the 8 u32
/// result words as named `let` bindings into the caller's scope.
///
/// **Midstate optimisation**: rounds 0..7 of block 1's compress depend only on
/// the SHA initial state and W[0..7] = base — both loop-invariant. cuda-oxide's
/// codegen wasn't const-folding the round-0..7 `llvm.fshr.i32(const,const,k)`
/// calls out of the inner loop, so we precompute the post-round-7 state
/// (`$st0..$st7`) on the host and pass it in. The kernel starts compress at
/// round 8.
///
/// W[16..22] of the message schedule still references W[0..7] = base, so we
/// also pass `$b0..$b7` so the macro can do sig0(base)+base adds. LLVM is
/// happy with those because `$b*` are kernel `.param` values.
///
/// Args:
///   $st0..$st7: u32 — state after rounds 0..7 of block 1 (host-precomputed)
///   $b0..$b7  : u32 — base bytes 0..32 as BE words (b0 holds bytes 0..4)
///   $s0..$s3  : u32 — seed bytes 0..16 BE-packed
///   $o0..$o7  : u32 — owner bytes 0..32 as BE words
///   $h0..$h7  : ident — caller-named locals to receive the digest words.
#[macro_export]
macro_rules! sha256_80 {
    ($st0:expr, $st1:expr, $st2:expr, $st3:expr,
     $st4:expr, $st5:expr, $st6:expr, $st7:expr,
     $b0:expr, $b1:expr, $b2:expr, $b3:expr,
     $b4:expr, $b5:expr, $b6:expr, $b7:expr,
     $s0:expr, $s1:expr, $s2:expr, $s3:expr,
     $o0:expr, $o1:expr, $o2:expr, $o3:expr,
     $o4:expr, $o5:expr, $o6:expr, $o7:expr,
     $h0:ident, $h1:ident, $h2:ident, $h3:ident,
     $h4:ident, $h5:ident, $h6:ident, $h7:ident) => {
        let __mid_a: u32 = $st0; let __mid_b: u32 = $st1;
        let __mid_c: u32 = $st2; let __mid_d: u32 = $st3;
        let __mid_e: u32 = $st4; let __mid_f: u32 = $st5;
        let __mid_g: u32 = $st6; let __mid_h: u32 = $st7;
        let __base_w0: u32 = $b0; let __base_w1: u32 = $b1;
        let __base_w2: u32 = $b2; let __base_w3: u32 = $b3;
        let __base_w4: u32 = $b4; let __base_w5: u32 = $b5;
        let __base_w6: u32 = $b6; let __base_w7: u32 = $b7;
        let __seed_w0: u32 = $s0; let __seed_w1: u32 = $s1;
        let __seed_w2: u32 = $s2; let __seed_w3: u32 = $s3;
        let __owner_w0: u32 = $o0; let __owner_w1: u32 = $o1;
        let __owner_w2: u32 = $o2; let __owner_w3: u32 = $o3;
        let __owner_w4: u32 = $o4; let __owner_w5: u32 = $o5;
        let __owner_w6: u32 = $o6; let __owner_w7: u32 = $o7;
""")

# ─── block 0: ma00..ma07 = base words, ma08..ma11 = seed, ma12..ma15 = owner[0..16]
# Everything sourced from pre-loaded u32 locals — zero byte loads inside the
# macro body. The caller's prologue is what actually fetches base/owner from
# global memory, and rustc/LLVM hoists that out of the loop.
def emit_load_m_block0_pure_u32(indent):
    for i in range(16):
        if i < 8:
            src = f"__base_w{i}"
        elif i < 12:
            src = f"__seed_w{i - 8}"
        else:
            src = f"__owner_w{i - 12}"
        print(f"{indent}let ma{i:02}: u32 = {src};")

emit_load_m_block0_pure_u32(indent="        ")
emit_extend_m("a", indent="        ")

# Block 1: init a..h to the host-precomputed midstate (post round-7), then run
# rounds 8..63. The canonical SHA add-back still uses the original IV.
midstate_vars = tuple(f"__mid_{c}" for c in ("a","b","c","d","e","f","g","h"))
iv_vars = tuple(f"0x{INIT_STATE[i]:08x}u32" for i in range(8))
out_state_a = ("a0", "a1", "a2", "a3", "a4", "a5", "a6", "a7")
emit_compress("a", midstate_vars, iv_vars, out_state_a, indent="        ", start_round=8)

# ─── block 1: ma00 = owner[16..20], ma01 = owner[20..24], ma02 = owner[24..28],
#             ma03 = owner[28..32], then padding + bitlen — all literal consts.
def emit_load_m_block1_pure_u32(indent):
    for i in range(16):
        if i < 4:
            src = f"__owner_w{i + 4}"
        elif i == 4:
            src = "0x80000000u32"  # 0x80, then 24 zero bits
        elif i == 15:
            src = "0x00000280u32"  # bit-length 640 = 0x280
        else:
            src = "0u32"
        print(f"{indent}let mb{i:02}: u32 = {src};")

emit_load_m_block1_pure_u32(indent="        ")
emit_extend_m("b", indent="        ")

# Block 2: init from block 1's output, run all 64 rounds, add back into same.
in_state_b = ("a0", "a1", "a2", "a3", "a4", "a5", "a6", "a7")
out_state_b = ("b0", "b1", "b2", "b3", "b4", "b5", "b6", "b7")
emit_compress("b", in_state_b, in_state_b, out_state_b, indent="        ")

# ─── inject named outputs ───────────────────────────────────────────────────
print("""        let $h0 = b0;
        let $h1 = b1;
        let $h2 = b2;
        let $h3 = b3;
        let $h4 = b4;
        let $h5 = b5;
        let $h6 = b6;
        let $h7 = b7;
    };
}
""")
